mat=
[
{"Matvare":"Berlinerbolle, kjøpt","Kilokalorier":439,"Fett":23.2,"Karbohydrat":49.2,"Protein":7.3,"Kategori":"Brødmat","underkategori":"Bolle/lefse"},
{"Matvare":"Bolle, med sjokoladebiter","Kilokalorier":378,"Fett":13.3,"Karbohydrat":55.3,"Protein":7.7,"Kategori":"Brødmat","underkategori":"Bolle/lefse"},
{"Matvare":"Bolle, uten rosiner, kjøpt","Kilokalorier":361,"Fett":11.3,"Karbohydrat":55.7,"Protein":7.7,"Kategori":"Brødmat","underkategori":"Bolle/lefse"},
{"Matvare":"Kanelbolle, skillingsbolle, med sukkerstrø, kjøpt","Kilokalorier":292,"Fett":5.2,"Karbohydrat":51.8,"Protein":8.4,"Kategori":"Brødmat","underkategori":"Bolle/lefse"},
{"Matvare":"Lefse, ferdig smurt, Vestlandslefsa","Kilokalorier":347,"Fett":17.2,"Karbohydrat":41.4,"Protein":5.8,"Kategori":"Brødmat","underkategori":"Bolle/lefse"},
{"Matvare":"Rosinbolle, kjøpt","Kilokalorier":357,"Fett":10.4,"Karbohydrat":56.9,"Protein":7.3,"Kategori":"Brødmat","underkategori":"Bolle/lefse"},
{"Matvare":"Baguette, fin, halvstekt, stekt","Kilokalorier":260,"Fett":1.4,"Karbohydrat":50.6,"Protein":9.9,"Kategori":"Brødmat","underkategori":"Brød"},
{"Matvare":"Brød, ekstra grovt (75-100 %), karbohydratredusert, kjøpt, Fiber og frø","Kilokalorier":260,"Fett":11,"Karbohydrat":19.7,"Protein":15.9,"Kategori":"Brødmat","underkategori":"Brød"},
{"Matvare":"Brød, grovt (50-75 %), kjøpt","Kilokalorier":237,"Fett":2.3,"Karbohydrat":42.2,"Protein":9,"Kategori":"Brødmat","underkategori":"Brød"},
{"Matvare":"Brød, halvgrovt (25-50 %), kjøpt","Kilokalorier":231,"Fett":2.4,"Karbohydrat":42.2,"Protein":8,"Kategori":"Brødmat","underkategori":"Brød"},
{"Matvare":"Focaccia","Kilokalorier":316,"Fett":12.2,"Karbohydrat":43.3,"Protein":7.1,"Kategori":"Brødmat","underkategori":"Brød"},
{"Matvare":"Hamburgerbrød, fint, kjøpt","Kilokalorier":303,"Fett":8.3,"Karbohydrat":49.5,"Protein":6.6,"Kategori":"Brødmat","underkategori":"Brød"},
{"Matvare":"Loff, fint brød (0-25 %), kjøpt","Kilokalorier":272,"Fett":2.3,"Karbohydrat":53,"Protein":8.6,"Kategori":"Brødmat","underkategori":"Brød"},
{"Matvare":"Pitabrød, fint, kjøpt","Kilokalorier":235,"Fett":1.1,"Karbohydrat":47.3,"Protein":7.4,"Kategori":"Brødmat","underkategori":"Brød"},
{"Matvare":"Polarbrød, hvete","Kilokalorier":321,"Fett":5.1,"Karbohydrat":58.4,"Protein":9.1,"Kategori":"Brødmat","underkategori":"Brød"},
{"Matvare":"Pølsebrød, fint, kjøpt","Kilokalorier":304,"Fett":8.2,"Karbohydrat":50.1,"Protein":6.5,"Kategori":"Brødmat","underkategori":"Brød"},
{"Matvare":"Rugbrød, fint (0-25 %), kjøpt","Kilokalorier":248,"Fett":2.6,"Karbohydrat":45.7,"Protein":7.9,"Kategori":"Brødmat","underkategori":"Brød"},
{"Matvare":"Rugbrød, grovt (50-75 %), kjøpt","Kilokalorier":259,"Fett":2.4,"Karbohydrat":48.4,"Protein":6.9,"Kategori":"Brødmat","underkategori":"Brød"},
{"Matvare":"Rundstykke, fint, kjøpt","Kilokalorier":284,"Fett":3.3,"Karbohydrat":53.4,"Protein":8.7,"Kategori":"Brødmat","underkategori":"Brød"},
{"Matvare":"Rundstykke, grovt, kjøpt","Kilokalorier":256,"Fett":5.2,"Karbohydrat":43,"Protein":7.6,"Kategori":"Brødmat","underkategori":"Brød"},
{"Matvare":"Terte, uten fyll","Kilokalorier":527,"Fett":29.8,"Karbohydrat":56.4,"Protein":7.5,"Kategori":"Brødmat","underkategori":"Brød"},
{"Matvare":"Gjær, tørrgjær","Kilokalorier":341,"Fett":7.6,"Karbohydrat":14.3,"Protein":40.4,"Kategori":"Brødmat","underkategori":"diverse"},
{"Matvare":"Riskaker, lettsaltet","Kilokalorier":380,"Fett":3,"Karbohydrat":78,"Protein":8,"Kategori":"Brødmat","underkategori":"diverse"},
{"Matvare":"Flatbrød, kjøpt","Kilokalorier":340,"Fett":1.2,"Karbohydrat":67.4,"Protein":10.4,"Kategori":"Brødmat","underkategori":"Flat-/knekkebrød"},
{"Matvare":"Knekkebrød, havre","Kilokalorier":364,"Fett":5.3,"Karbohydrat":61,"Protein":13,"Kategori":"Brødmat","underkategori":"Flat-/knekkebrød"},
{"Matvare":"Knekkebrød, lyst","Kilokalorier":403,"Fett":8.5,"Karbohydrat":67.7,"Protein":11,"Kategori":"Brødmat","underkategori":"Flat-/knekkebrød"},
{"Matvare":"Knekkebrød, med ekstra fiber","Kilokalorier":349,"Fett":8,"Karbohydrat":43.2,"Protein":13,"Kategori":"Brødmat","underkategori":"Flat-/knekkebrød"},
{"Matvare":"Knekkebrød, rug, Husman","Kilokalorier":319,"Fett":1.1,"Karbohydrat":62.3,"Protein":7.8,"Kategori":"Brødmat","underkategori":"Flat-/knekkebrød"},
{"Matvare":"Knekkebrød, rug, Ryvita","Kilokalorier":336,"Fett":1.1,"Karbohydrat":64.6,"Protein":9.1,"Kategori":"Brødmat","underkategori":"Flat-/knekkebrød"},
{"Matvare":"Croissant, uten fyll, kjøpt","Kilokalorier":404,"Fett":21.4,"Karbohydrat":43.7,"Protein":8.5,"Kategori":"Brødmat","underkategori":"Kake"},
{"Matvare":"Daimkake","Kilokalorier":379,"Fett":24.8,"Karbohydrat":32.7,"Protein":5.5,"Kategori":"Brødmat","underkategori":"Kake"},
{"Matvare":"Delfiakake","Kilokalorier":530,"Fett":43,"Karbohydrat":30.1,"Protein":4.6,"Kategori":"Brødmat","underkategori":"Kake"},
{"Matvare":"Donuts, med sjokoladeglasur, kjøpt","Kilokalorier":497,"Fett":37.3,"Karbohydrat":33.3,"Protein":6.2,"Kategori":"Brødmat","underkategori":"Kake"},
{"Matvare":"Formkake, fet, dansk sandkake","Kilokalorier":413,"Fett":23,"Karbohydrat":46.4,"Protein":4.9,"Kategori":"Brødmat","underkategori":"Kake"},
{"Matvare":"Formkake, marmor","Kilokalorier":368,"Fett":17.4,"Karbohydrat":45.1,"Protein":7,"Kategori":"Brødmat","underkategori":"Kake"},
{"Matvare":"Formkake, med epler","Kilokalorier":265,"Fett":13.5,"Karbohydrat":31.4,"Protein":3.8,"Kategori":"Brødmat","underkategori":"Kake"},
{"Matvare":"Fyrstekake, med mandler","Kilokalorier":430,"Fett":21.9,"Karbohydrat":48.5,"Protein":8.5,"Kategori":"Brødmat","underkategori":"Kake"},
{"Matvare":"Gulrotkake, med ostekrem, kjøpt","Kilokalorier":331,"Fett":12.4,"Karbohydrat":50.3,"Protein":3.8,"Kategori":"Brødmat","underkategori":"Kake"},
{"Matvare":"Hvite kakemenn","Kilokalorier":371,"Fett":9.3,"Karbohydrat":64.5,"Protein":6.5,"Kategori":"Brødmat","underkategori":"Kake"},
{"Matvare":"Kransekake","Kilokalorier":480,"Fett":24.5,"Karbohydrat":51.3,"Protein":11.2,"Kategori":"Brødmat","underkategori":"Kake"},
{"Matvare":"Muffins","Kilokalorier":411,"Fett":20.2,"Karbohydrat":50.6,"Protein":6.2,"Kategori":"Brødmat","underkategori":"Kake"},
{"Matvare":"Pepperkaker","Kilokalorier":459,"Fett":15.9,"Karbohydrat":72.9,"Protein":5.3,"Kategori":"Brødmat","underkategori":"Kake"},
{"Matvare":"Rullekake, med smørkrem av margarin","Kilokalorier":398,"Fett":19.8,"Karbohydrat":48.3,"Protein":6.3,"Kategori":"Brødmat","underkategori":"Kake"},
{"Matvare":"Sarah Bernhard-kake","Kilokalorier":467,"Fett":29.6,"Karbohydrat":40.5,"Protein":8,"Kategori":"Brødmat","underkategori":"Kake"},
{"Matvare":"Scones, grove, med melk","Kilokalorier":301,"Fett":8.3,"Karbohydrat":45.6,"Protein":8.8,"Kategori":"Brødmat","underkategori":"Kake"},
{"Matvare":"Vafler, grove","Kilokalorier":226,"Fett":8.9,"Karbohydrat":27.1,"Protein":8.5,"Kategori":"Brødmat","underkategori":"Kake"},
{"Matvare":"Vafler, med egg, lettmelk","Kilokalorier":218,"Fett":8.8,"Karbohydrat":27.2,"Protein":7,"Kategori":"Brødmat","underkategori":"Kake"},
{"Matvare":"Wienerbrød, med eggekrem","Kilokalorier":401,"Fett":24.4,"Karbohydrat":38,"Protein":6.5,"Kategori":"Brødmat","underkategori":"Kake"},
{"Matvare":"Wienerkringle, med mandelfyll","Kilokalorier":496,"Fett":35.8,"Karbohydrat":36.4,"Protein":6.2,"Kategori":"Brødmat","underkategori":"Kake"},
{"Matvare":"Biscotti","Kilokalorier":449,"Fett":15.9,"Karbohydrat":61.6,"Protein":12.6,"Kategori":"Brødmat","underkategori":"Kjeks"},
{"Matvare":"Kjeks, salt, fet, Ritz, Seltiner","Kilokalorier":466,"Fett":23.4,"Karbohydrat":53.5,"Protein":8.6,"Kategori":"Brødmat","underkategori":"Kjeks"},
{"Matvare":"Kjeks, søt,  sjokoladebiter, cookies, store","Kilokalorier":420,"Fett":16.4,"Karbohydrat":60.7,"Protein":6.1,"Kategori":"Brødmat","underkategori":"Kjeks"},
{"Matvare":"Kjeks, søt, Ballerina","Kilokalorier":465,"Fett":20.7,"Karbohydrat":62.4,"Protein":6.1,"Kategori":"Brødmat","underkategori":"Kjeks"},
{"Matvare":"Kjeks, søt, Gjende","Kilokalorier":463,"Fett":18.6,"Karbohydrat":65.4,"Protein":6.6,"Kategori":"Brødmat","underkategori":"Kjeks"},
{"Matvare":"Kjeks, søt, grov, Digestive","Kilokalorier":470,"Fett":20.3,"Karbohydrat":62.9,"Protein":7.2,"Kategori":"Brødmat","underkategori":"Kjeks"},
{"Matvare":"Kjeks, søt, havre, Bixit","Kilokalorier":458,"Fett":19.1,"Karbohydrat":60.9,"Protein":7.7,"Kategori":"Brødmat","underkategori":"Kjeks"},
{"Matvare":"Kjeks, søt, vaffel, fylt","Kilokalorier":512,"Fett":23.5,"Karbohydrat":70.3,"Protein":4.1,"Kategori":"Brødmat","underkategori":"Kjeks"},
{"Matvare":"Egg, rå","Kilokalorier":149,"Fett":10.6,"Karbohydrat":0.3,"Protein":13,"Kategori":"Diverse","underkategori":"Egg"},
{"Matvare":"Miso, fermentert soyabønnepasta","Kilokalorier":172,"Fett":4.6,"Karbohydrat":21,"Protein":10.5,"Kategori":"Diverse","underkategori":"Middag"},
{"Matvare":"Pizzabunn, uten fyll","Kilokalorier":244,"Fett":3.3,"Karbohydrat":44.8,"Protein":7.5,"Kategori":"Diverse","underkategori":"Middag"},
{"Matvare":"Potetsalat, med ekte majones","Kilokalorier":325,"Fett":29.7,"Karbohydrat":12.3,"Protein":1.6,"Kategori":"Diverse","underkategori":"Middag"},
{"Matvare":"Potetsalat, med lettmajones (40 % fett)","Kilokalorier":195,"Fett":14.5,"Karbohydrat":14.1,"Protein":1.4,"Kategori":"Diverse","underkategori":"Middag"},
{"Matvare":"Potetsalat, med lettrømme","Kilokalorier":107,"Fett":5.3,"Karbohydrat":12.2,"Protein":1.9,"Kategori":"Diverse","underkategori":"Middag"},
{"Matvare":"Soyaburger, stekt i vegetabilsk olje","Kilokalorier":195,"Fett":11,"Karbohydrat":11.7,"Protein":10.6,"Kategori":"Diverse","underkategori":"Middag"},
{"Matvare":"Soyapølse, hermetisk","Kilokalorier":201,"Fett":15,"Karbohydrat":3.5,"Protein":12,"Kategori":"Diverse","underkategori":"Middag"},
{"Matvare":"Soyasaus","Kilokalorier":84,"Fett":0,"Karbohydrat":17.9,"Protein":3,"Kategori":"Diverse","underkategori":"Middag"},
{"Matvare":"Tacosaus","Kilokalorier":27,"Fett":0.1,"Karbohydrat":4,"Protein":1.9,"Kategori":"Diverse","underkategori":"Middag"},
{"Matvare":"Tacoskjell","Kilokalorier":462,"Fett":23.4,"Karbohydrat":55.3,"Protein":5.7,"Kategori":"Diverse","underkategori":"Middag"},
{"Matvare":"Tofu, soyabønneost","Kilokalorier":77,"Fett":4.2,"Karbohydrat":0.6,"Protein":8.1,"Kategori":"Diverse","underkategori":"Middag"},
{"Matvare":"Tortilla, maislefse","Kilokalorier":258,"Fett":2.8,"Karbohydrat":50.1,"Protein":6.2,"Kategori":"Diverse","underkategori":"Middag"},
{"Matvare":"Wokblanding, klassisk","Kilokalorier":34,"Fett":0.3,"Karbohydrat":4.8,"Protein":1.9,"Kategori":"Diverse","underkategori":"middag"},
{"Matvare":"Taco kryddermix","Kilokalorier":226,"Fett":3.5,"Karbohydrat":36.6,"Protein":5.9,"Kategori":"Diverse","underkategori":"Salt"},
{"Matvare":"Urtesalt","Kilokalorier":47,"Fett":1.7,"Karbohydrat":0.3,"Protein":7.6,"Kategori":"Diverse","underkategori":"Salt"},
{"Matvare":"Honning","Kilokalorier":317,"Fett":0,"Karbohydrat":78.9,"Protein":0.3,"Kategori":"Diverse","underkategori":"Søtt"},
{"Matvare":"Melis","Kilokalorier":400,"Fett":0,"Karbohydrat":100,"Protein":0,"Kategori":"Diverse","underkategori":"Søtt"},
{"Matvare":"Sirup","Kilokalorier":297,"Fett":0,"Karbohydrat":74.1,"Protein":0.1,"Kategori":"Diverse","underkategori":"Søtt"},
{"Matvare":"Sukker, brunt","Kilokalorier":376,"Fett":0,"Karbohydrat":94,"Protein":0,"Kategori":"Diverse","underkategori":"Søtt"},
{"Matvare":"Sukker, hvitt","Kilokalorier":400,"Fett":0,"Karbohydrat":100,"Protein":0,"Kategori":"Diverse","underkategori":"Søtt"},
{"Matvare":"Vaniljesukker","Kilokalorier":364,"Fett":0,"Karbohydrat":91.1,"Protein":0,"Kategori":"Diverse","underkategori":"Søtt"},
{"Matvare":"Cider, søt, 4,5 vol-% alkohol","Kilokalorier":59,"Fett":0,"Karbohydrat":8.5,"Protein":0,"Kategori":"Drikke","underkategori":"Alkohol"},
{"Matvare":"Dessertvin, ekstra søt, musserende","Kilokalorier":76,"Fett":0,"Karbohydrat":3.7,"Protein":0.2,"Kategori":"Drikke","underkategori":"Alkohol"},
{"Matvare":"Gulløl, 5,7 vol-% alkohol","Kilokalorier":58,"Fett":0,"Karbohydrat":6.1,"Protein":0.5,"Kategori":"Drikke","underkategori":"Alkohol"},
{"Matvare":"Hvitvin, halvtørr, 10 vol-% alkohol","Kilokalorier":72,"Fett":0,"Karbohydrat":0.6,"Protein":0.1,"Kategori":"Drikke","underkategori":"Alkohol"},
{"Matvare":"Lettøl, lett, 2,5 vol-% alkohol","Kilokalorier":25,"Fett":0,"Karbohydrat":2.5,"Protein":0.2,"Kategori":"Drikke","underkategori":"Alkohol"},
{"Matvare":"Likør, 35 vol-% alkohol","Kilokalorier":313,"Fett":0,"Karbohydrat":27.5,"Protein":0,"Kategori":"Drikke","underkategori":"Alkohol"},
{"Matvare":"Pils, 4,7 vol-% alkohol","Kilokalorier":41,"Fett":0,"Karbohydrat":3.2,"Protein":0.4,"Kategori":"Drikke","underkategori":"Alkohol"},
{"Matvare":"Rødvin, 12 vol-% alkohol","Kilokalorier":74,"Fett":0,"Karbohydrat":0.7,"Protein":0.1,"Kategori":"Drikke","underkategori":"Alkohol"},
{"Matvare":"Sterkvin, søt, portvin, 20 vol-% alkohol","Kilokalorier":151,"Fett":0,"Karbohydrat":9.6,"Protein":0.1,"Kategori":"Drikke","underkategori":"Alkohol"},
{"Matvare":"Sterkøl, bokkøl, 6,5 vol-% alkohol","Kilokalorier":63,"Fett":0,"Karbohydrat":6,"Protein":0.7,"Kategori":"Drikke","underkategori":"Alkohol"},
{"Matvare":"Vin, alkoholfri","Kilokalorier":17,"Fett":0,"Karbohydrat":4,"Protein":0.2,"Kategori":"Drikke","underkategori":"Alkohol"},
{"Matvare":"Vin, alkoholsvak","Kilokalorier":36,"Fett":0,"Karbohydrat":6.1,"Protein":0,"Kategori":"Drikke","underkategori":"Alkohol"},
{"Matvare":"Øl, alkoholfritt","Kilokalorier":24,"Fett":0,"Karbohydrat":5,"Protein":0.4,"Kategori":"Drikke","underkategori":"Alkohol"},
{"Matvare":"Øl, redusert energiinnhold, lavkarbo","Kilokalorier":32,"Fett":0,"Karbohydrat":1,"Protein":0.4,"Kategori":"Drikke","underkategori":"Alkohol"},
{"Matvare":"Espresso, enkel","Kilokalorier":9,"Fett":0,"Karbohydrat":1.3,"Protein":0.9,"Kategori":"Drikke","underkategori":"Diverse"},
{"Matvare":"Kokosmelk","Kilokalorier":209,"Fett":21.3,"Karbohydrat":1.5,"Protein":2,"Kategori":"Drikke","underkategori":"Diverse"},
{"Matvare":"Mandeldrikke","Kilokalorier":26,"Fett":1.3,"Karbohydrat":3.5,"Protein":0,"Kategori":"Drikke","underkategori":"Diverse"},
{"Matvare":"Risdrikke","Kilokalorier":36,"Fett":0.9,"Karbohydrat":6.9,"Protein":0.1,"Kategori":"Drikke","underkategori":"Diverse"},
{"Matvare":"Soyadrikke, tilsatt kalsium, søtet","Kilokalorier":44,"Fett":2.4,"Karbohydrat":2.2,"Protein":3.1,"Kategori":"Drikke","underkategori":"Diverse"},
{"Matvare":"Ananasjuice","Kilokalorier":50,"Fett":0.1,"Karbohydrat":11.8,"Protein":0.4,"Kategori":"Drikke","underkategori":"Juice"},
{"Matvare":"Appelsinjuice","Kilokalorier":43,"Fett":0.2,"Karbohydrat":9.6,"Protein":0.7,"Kategori":"Drikke","underkategori":"Juice"},
{"Matvare":"Eplejuice","Kilokalorier":42,"Fett":0.1,"Karbohydrat":10.2,"Protein":0,"Kategori":"Drikke","underkategori":"Juice"},
{"Matvare":"Brus, cola, med sukker","Kilokalorier":42,"Fett":0,"Karbohydrat":10.6,"Protein":0,"Kategori":"Drikke","underkategori":"Søt"},
{"Matvare":"Iste, Nestea","Kilokalorier":18,"Fett":0,"Karbohydrat":4.5,"Protein":0,"Kategori":"Drikke","underkategori":"Søt"},
{"Matvare":"Kakao, med lettmelk, tilberedt","Kilokalorier":87,"Fett":2.3,"Karbohydrat":12,"Protein":4,"Kategori":"Drikke","underkategori":"Søt"},
{"Matvare":"Milkshake, sjokoladesmak","Kilokalorier":78,"Fett":1.5,"Karbohydrat":12,"Protein":4.1,"Kategori":"Drikke","underkategori":"Søt"},
{"Matvare":"Smoothie, med yoghurt, juice, banan og bær","Kilokalorier":60,"Fett":1.2,"Karbohydrat":9.9,"Protein":1.7,"Kategori":"Drikke","underkategori":"Søt"},
{"Matvare":"Solbærsirup, drikkeklar","Kilokalorier":32,"Fett":0,"Karbohydrat":7.9,"Protein":0.1,"Kategori":"Drikke","underkategori":"Søt"},
{"Matvare":"Bjørnebær, rå","Kilokalorier":40,"Fett":0.5,"Karbohydrat":4.9,"Protein":1.4,"Kategori":"Frukt/Bær","underkategori":"Bær"},
{"Matvare":"Blåbær, rå","Kilokalorier":51,"Fett":0.9,"Karbohydrat":7.5,"Protein":1,"Kategori":"Frukt/Bær","underkategori":"Bær"},
{"Matvare":"Bringebær, rå","Kilokalorier":29,"Fett":0.4,"Karbohydrat":3.2,"Protein":1.1,"Kategori":"Frukt/Bær","underkategori":"Bær"},
{"Matvare":"Hyllebær, rå","Kilokalorier":47,"Fett":0.5,"Karbohydrat":6.5,"Protein":0.7,"Kategori":"Frukt/Bær","underkategori":"Bær"},
{"Matvare":"Jordbær, rå","Kilokalorier":34,"Fett":0.2,"Karbohydrat":6.6,"Protein":0.5,"Kategori":"Frukt/Bær","underkategori":"Bær"},
{"Matvare":"Kirsebær, rå","Kilokalorier":41,"Fett":0,"Karbohydrat":9,"Protein":0.7,"Kategori":"Frukt/Bær","underkategori":"Bær"},
{"Matvare":"Krekling, krøkebær, rå","Kilokalorier":38,"Fett":0.5,"Karbohydrat":5.3,"Protein":0.3,"Kategori":"Frukt/Bær","underkategori":"Bær"},
{"Matvare":"Moreller, rå","Kilokalorier":52,"Fett":0.1,"Karbohydrat":11.3,"Protein":0.9,"Kategori":"Frukt/Bær","underkategori":"Bær"},
{"Matvare":"Rips, rå","Kilokalorier":53,"Fett":1.2,"Karbohydrat":6.9,"Protein":1.2,"Kategori":"Frukt/Bær","underkategori":"Bær"},
{"Matvare":"Solbær, rå","Kilokalorier":55,"Fett":1,"Karbohydrat":7.6,"Protein":1.3,"Kategori":"Frukt/Bær","underkategori":"Bær"},
{"Matvare":"Stikkelsbær, rå","Kilokalorier":37,"Fett":0.6,"Karbohydrat":5.4,"Protein":0.8,"Kategori":"Frukt/Bær","underkategori":"Bær"},
{"Matvare":"Tranebær, rå","Kilokalorier":28,"Fett":0.1,"Karbohydrat":4,"Protein":0.4,"Kategori":"Frukt/Bær","underkategori":"Bær"},
{"Matvare":"Tyttebær, rå","Kilokalorier":44,"Fett":0.6,"Karbohydrat":7,"Protein":0.7,"Kategori":"Frukt/Bær","underkategori":"Bær"},
{"Matvare":"Ananas, hermetisk, med egen saft","Kilokalorier":51,"Fett":0,"Karbohydrat":12.2,"Protein":0.3,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Ananas, hermetisk, med sukkerlake","Kilokalorier":69,"Fett":0,"Karbohydrat":16.5,"Protein":0.5,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Ananas, rå","Kilokalorier":51,"Fett":0.1,"Karbohydrat":11.4,"Protein":0.5,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Appelsin, rå","Kilokalorier":37,"Fett":0.1,"Karbohydrat":7.2,"Protein":0.9,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Aprikos, hermetisk, med sukkerlake","Kilokalorier":70,"Fett":0,"Karbohydrat":16.1,"Protein":0.5,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Aprikos, rå","Kilokalorier":52,"Fett":0.4,"Karbohydrat":9.7,"Protein":1.4,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Aprikos, tørket","Kilokalorier":181,"Fett":0.5,"Karbohydrat":39.4,"Protein":2.2,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Banan, rå","Kilokalorier":83,"Fett":0.3,"Karbohydrat":18.1,"Protein":1.1,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Carambola, stjernefrukt, rå","Kilokalorier":36,"Fett":0.3,"Karbohydrat":7.3,"Protein":0.5,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Daddel, tørket","Kilokalorier":299,"Fett":0.2,"Karbohydrat":68,"Protein":3.3,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Drue, blå, rå","Kilokalorier":53,"Fett":0.2,"Karbohydrat":11.7,"Protein":0.7,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Drue, grønn, rå","Kilokalorier":70,"Fett":0.2,"Karbohydrat":16,"Protein":0.7,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Drue, uspesifisert, rå","Kilokalorier":62,"Fett":0.2,"Karbohydrat":13.8,"Protein":0.7,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Eple, Rød aroma, rå","Kilokalorier":50,"Fett":0,"Karbohydrat":11.2,"Protein":0,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Fersken, hermetisk, med egen saft","Kilokalorier":43,"Fett":0,"Karbohydrat":9.7,"Protein":0.6,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Fersken, hermetisk, med sukkerlake","Kilokalorier":60,"Fett":0,"Karbohydrat":14,"Protein":0.5,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Fersken, rå","Kilokalorier":42,"Fett":0.2,"Karbohydrat":8.4,"Protein":0.9,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Fiken, tørket","Kilokalorier":253,"Fett":0.9,"Karbohydrat":53,"Protein":3.3,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Granateple, rå","Kilokalorier":80,"Fett":1.2,"Karbohydrat":13.7,"Protein":1.7,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Grapefrukt, rå","Kilokalorier":34,"Fett":0.1,"Karbohydrat":6.9,"Protein":0.9,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Guava, rå","Kilokalorier":39,"Fett":1,"Karbohydrat":5,"Protein":0.8,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Honningmelon, rå","Kilokalorier":37,"Fett":0.1,"Karbohydrat":8.1,"Protein":0.5,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Kiwi, rå","Kilokalorier":50,"Fett":0.9,"Karbohydrat":8.3,"Protein":0.8,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Klementin, rå","Kilokalorier":45,"Fett":0.2,"Karbohydrat":9.2,"Protein":0.8,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Lime, rå","Kilokalorier":17,"Fett":0.2,"Karbohydrat":1.7,"Protein":0.7,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Litchi, rå","Kilokalorier":71,"Fett":0.4,"Karbohydrat":15.2,"Protein":0.8,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Mango, rå","Kilokalorier":49,"Fett":0.3,"Karbohydrat":10.4,"Protein":0.7,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Molter, rå","Kilokalorier":46,"Fett":1.1,"Karbohydrat":4.4,"Protein":1.6,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Nektarin, rå","Kilokalorier":48,"Fett":0.3,"Karbohydrat":9.8,"Protein":1,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Nype, rå","Kilokalorier":53,"Fett":0.5,"Karbohydrat":8.6,"Protein":0.6,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Papaya, rå","Kilokalorier":47,"Fett":0.3,"Karbohydrat":9.5,"Protein":0.7,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Papaya, tørket","Kilokalorier":259,"Fett":0.6,"Karbohydrat":57.6,"Protein":3.4,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Paradisepler, rå","Kilokalorier":31,"Fett":0.3,"Karbohydrat":5.8,"Protein":0.4,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Pasjonsfrukt, rå","Kilokalorier":44,"Fett":0.4,"Karbohydrat":5.8,"Protein":2.6,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Physalis, rå","Kilokalorier":64,"Fett":0.6,"Karbohydrat":10.7,"Protein":1.8,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Plomme, rå","Kilokalorier":44,"Fett":0.1,"Karbohydrat":9.3,"Protein":0.5,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Pære, uspesifisert, rå","Kilokalorier":44,"Fett":0.1,"Karbohydrat":8.8,"Protein":0.4,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Rabarbra, rå","Kilokalorier":20,"Fett":0.2,"Karbohydrat":1.9,"Protein":0.9,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Rosiner","Kilokalorier":277,"Fett":1,"Karbohydrat":62.6,"Protein":3,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Sharon, kakifrukt, rå","Kilokalorier":65,"Fett":0.3,"Karbohydrat":12,"Protein":0.7,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Sitron, rå","Kilokalorier":23,"Fett":0.3,"Karbohydrat":2.5,"Protein":1.1,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Svisker","Kilokalorier":168,"Fett":0.3,"Karbohydrat":36.5,"Protein":2.3,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Vannmelon, rå","Kilokalorier":35,"Fett":0.1,"Karbohydrat":7.6,"Protein":0.8,"Kategori":"Frukt/Bær","underkategori":"Frukt"},
{"Matvare":"Aspargesbønner, rå","Kilokalorier":27,"Fett":0.1,"Karbohydrat":3.4,"Protein":1.7,"Kategori":"Grønnsaker","underkategori":"Bønner/erter"},
{"Matvare":"Brune bønner, tørre","Kilokalorier":313,"Fett":1.5,"Karbohydrat":44.6,"Protein":22,"Kategori":"Grønnsaker","underkategori":"Bønner/erter"},
{"Matvare":"Erter, fryst","Kilokalorier":68,"Fett":0.4,"Karbohydrat":8,"Protein":5.2,"Kategori":"Grønnsaker","underkategori":"Bønner/erter"},
{"Matvare":"Erter, grønne, hermetisk, avrent","Kilokalorier":64,"Fett":1,"Karbohydrat":7,"Protein":4.3,"Kategori":"Grønnsaker","underkategori":"Bønner/erter"},
{"Matvare":"Hvite bønner, tørre","Kilokalorier":312,"Fett":0.8,"Karbohydrat":45.2,"Protein":23.4,"Kategori":"Grønnsaker","underkategori":"Bønner/erter"},
{"Matvare":"Kikerter, hermetiske","Kilokalorier":124,"Fett":2.5,"Karbohydrat":14.8,"Protein":7.5,"Kategori":"Grønnsaker","underkategori":"Bønner/erter"},
{"Matvare":"Kikerter, tørre","Kilokalorier":341,"Fett":5.4,"Karbohydrat":46.4,"Protein":21.3,"Kategori":"Grønnsaker","underkategori":"Bønner/erter"},
{"Matvare":"Limabønner, smørbønner, tørr","Kilokalorier":307,"Fett":0.7,"Karbohydrat":44.4,"Protein":21.5,"Kategori":"Grønnsaker","underkategori":"Bønner/erter"},
{"Matvare":"Linser, grønne og brune, tørre","Kilokalorier":307,"Fett":2,"Karbohydrat":41.6,"Protein":25.1,"Kategori":"Grønnsaker","underkategori":"Bønner/erter"},
{"Matvare":"Linser, røde/rosa, tørr","Kilokalorier":346,"Fett":2.2,"Karbohydrat":52.3,"Protein":23.9,"Kategori":"Grønnsaker","underkategori":"Bønner/erter"},
{"Matvare":"Meterbønner, rå","Kilokalorier":45,"Fett":0.4,"Karbohydrat":7,"Protein":2.8,"Kategori":"Grønnsaker","underkategori":"Bønner/erter"},
{"Matvare":"Mungbønner, tørre","Kilokalorier":295,"Fett":1.1,"Karbohydrat":42.4,"Protein":23.9,"Kategori":"Grønnsaker","underkategori":"Bønner/erter"},
{"Matvare":"Røde bønner, tørre","Kilokalorier":294,"Fett":1.4,"Karbohydrat":40.5,"Protein":22.1,"Kategori":"Grønnsaker","underkategori":"Bønner/erter"},
{"Matvare":"Sukkererter, norsk, rå","Kilokalorier":42,"Fett":0.1,"Karbohydrat":5.3,"Protein":3.5,"Kategori":"Grønnsaker","underkategori":"Bønner/erter"},
{"Matvare":"Svarte bønner, hermetiske","Kilokalorier":106,"Fett":1,"Karbohydrat":12.8,"Protein":8.1,"Kategori":"Grønnsaker","underkategori":"Bønner/erter"},
{"Matvare":"Svartøyebønner, tørr","Kilokalorier":324,"Fett":1.3,"Karbohydrat":49.4,"Protein":23.5,"Kategori":"Grønnsaker","underkategori":"Bønner/erter"},
{"Matvare":"Alfalfaspirer, rå","Kilokalorier":27,"Fett":0.7,"Karbohydrat":0.3,"Protein":4,"Kategori":"Grønnsaker","underkategori":"diverse"},
{"Matvare":"Artiskokk, rå","Kilokalorier":28,"Fett":0.2,"Karbohydrat":1.3,"Protein":2.8,"Kategori":"Grønnsaker","underkategori":"diverse"},
{"Matvare":"Asparges, hermetisk, avrent","Kilokalorier":24,"Fett":0.6,"Karbohydrat":1.6,"Protein":2.1,"Kategori":"Grønnsaker","underkategori":"diverse"},
{"Matvare":"Asparges, rå","Kilokalorier":22,"Fett":0.1,"Karbohydrat":2,"Protein":2.2,"Kategori":"Grønnsaker","underkategori":"diverse"},
{"Matvare":"Aubergine, rå","Kilokalorier":20,"Fett":0.1,"Karbohydrat":2.5,"Protein":1.1,"Kategori":"Grønnsaker","underkategori":"diverse"},
{"Matvare":"Avocado, rå","Kilokalorier":191,"Fett":19.6,"Karbohydrat":0.4,"Protein":1.8,"Kategori":"Grønnsaker","underkategori":"diverse"},
{"Matvare":"Bønnespirer, mungbønnespirer, rå","Kilokalorier":41,"Fett":0.2,"Karbohydrat":5.9,"Protein":3,"Kategori":"Grønnsaker","underkategori":"diverse"},
{"Matvare":"Gresskar, rå","Kilokalorier":13,"Fett":0.1,"Karbohydrat":1.7,"Protein":1,"Kategori":"Grønnsaker","underkategori":"diverse"},
{"Matvare":"Mais, hermetisk","Kilokalorier":85,"Fett":1.1,"Karbohydrat":15.4,"Protein":2.5,"Kategori":"Grønnsaker","underkategori":"diverse"},
{"Matvare":"Mais, norsk, rå","Kilokalorier":85,"Fett":1.7,"Karbohydrat":12.6,"Protein":3.2,"Kategori":"Grønnsaker","underkategori":"diverse"},
{"Matvare":"Oliven, grønne, med paprikafyll","Kilokalorier":130,"Fett":13.1,"Karbohydrat":1.1,"Protein":0.6,"Kategori":"Grønnsaker","underkategori":"diverse"},
{"Matvare":"Oliven, sorte, i olje, hermetisk","Kilokalorier":348,"Fett":36,"Karbohydrat":1.8,"Protein":2.2,"Kategori":"Grønnsaker","underkategori":"diverse"},
{"Matvare":"Pomelo, rå","Kilokalorier":33,"Fett":0.2,"Karbohydrat":6.8,"Protein":0.6,"Kategori":"Grønnsaker","underkategori":"diverse"},
{"Matvare":"Squash, zucchini, rå","Kilokalorier":17,"Fett":0.2,"Karbohydrat":2.2,"Protein":1.3,"Kategori":"Grønnsaker","underkategori":"diverse"},
{"Matvare":"Stangselleri, norsk, rå","Kilokalorier":15,"Fett":0.1,"Karbohydrat":1.3,"Protein":1.1,"Kategori":"Grønnsaker","underkategori":"diverse"},
{"Matvare":"Basilikum, rå","Kilokalorier":21,"Fett":0.6,"Karbohydrat":0,"Protein":3.2,"Kategori":"Grønnsaker","underkategori":"Krydder/urter"},
{"Matvare":"Basilikum, tørket","Kilokalorier":244,"Fett":4.1,"Karbohydrat":10,"Protein":23,"Kategori":"Grønnsaker","underkategori":"Krydder/urter"},
{"Matvare":"Chili, rød, rå","Kilokalorier":35,"Fett":0.4,"Karbohydrat":5.3,"Protein":1.9,"Kategori":"Grønnsaker","underkategori":"Krydder/urter"},
{"Matvare":"Dill, rå","Kilokalorier":48,"Fett":1.1,"Karbohydrat":4.9,"Protein":3.5,"Kategori":"Grønnsaker","underkategori":"Krydder/urter"},
{"Matvare":"Fennikel, rå","Kilokalorier":19,"Fett":0.4,"Karbohydrat":1.8,"Protein":0.9,"Kategori":"Grønnsaker","underkategori":"Krydder/urter"},
{"Matvare":"Kardemomme, malt","Kilokalorier":321,"Fett":6.7,"Karbohydrat":40.5,"Protein":10.8,"Kategori":"Grønnsaker","underkategori":"Krydder/urter"},
{"Matvare":"Karri, malt","Kilokalorier":301,"Fett":14,"Karbohydrat":2.8,"Protein":14.3,"Kategori":"Grønnsaker","underkategori":"Krydder/urter"},
{"Matvare":"Karve, kummin, hel","Kilokalorier":334,"Fett":14.6,"Karbohydrat":11.9,"Protein":19.8,"Kategori":"Grønnsaker","underkategori":"Krydder/urter"},
{"Matvare":"Koriander, rå","Kilokalorier":24,"Fett":0.5,"Karbohydrat":1.2,"Protein":2.1,"Kategori":"Grønnsaker","underkategori":"Krydder/urter"},
{"Matvare":"Merian, tørket","Kilokalorier":276,"Fett":7,"Karbohydrat":20.3,"Protein":12.7,"Kategori":"Grønnsaker","underkategori":"Krydder/urter"},
{"Matvare":"Pastinakk, rå","Kilokalorier":65,"Fett":0.6,"Karbohydrat":11.2,"Protein":1.7,"Kategori":"Grønnsaker","underkategori":"Krydder/urter"},
{"Matvare":"Pepper, cayenne, rød","Kilokalorier":375,"Fett":17.3,"Karbohydrat":29.4,"Protein":12,"Kategori":"Grønnsaker","underkategori":"Krydder/urter"},
{"Matvare":"Pepper, hvit","Kilokalorier":283,"Fett":2.1,"Karbohydrat":42.4,"Protein":10.4,"Kategori":"Grønnsaker","underkategori":"Krydder/urter"},
{"Matvare":"Persille, norsk, rå","Kilokalorier":32,"Fett":0.4,"Karbohydrat":1.6,"Protein":3.1,"Kategori":"Grønnsaker","underkategori":"Krydder/urter"},
{"Matvare":"Rosmarin, rå","Kilokalorier":120,"Fett":5.9,"Karbohydrat":6.6,"Protein":3.3,"Kategori":"Grønnsaker","underkategori":"Krydder/urter"},
{"Matvare":"Safran, tørket","Kilokalorier":352,"Fett":5.8,"Karbohydrat":61.5,"Protein":11.4,"Kategori":"Grønnsaker","underkategori":"Krydder/urter"},
{"Matvare":"Timian, rå","Kilokalorier":107,"Fett":1.7,"Karbohydrat":10.4,"Protein":5.6,"Kategori":"Grønnsaker","underkategori":"Krydder/urter"},
{"Matvare":"Blomkål, norsk, rå","Kilokalorier":23,"Fett":0.2,"Karbohydrat":2.3,"Protein":1.9,"Kategori":"Grønnsaker","underkategori":"Kål"},
{"Matvare":"Brokkoli, norsk, rå","Kilokalorier":28,"Fett":0.3,"Karbohydrat":1.9,"Protein":3.2,"Kategori":"Grønnsaker","underkategori":"Kål"},
{"Matvare":"Grønnkål, rå","Kilokalorier":36,"Fett":0.7,"Karbohydrat":2.2,"Protein":3.3,"Kategori":"Grønnsaker","underkategori":"Kål"},
{"Matvare":"Hodekål, rå","Kilokalorier":32,"Fett":0.1,"Karbohydrat":5.2,"Protein":1.4,"Kategori":"Grønnsaker","underkategori":"Kål"},
{"Matvare":"Kinakål, norsk, rå","Kilokalorier":15,"Fett":0.1,"Karbohydrat":1.8,"Protein":1.1,"Kategori":"Grønnsaker","underkategori":"Kål"},
{"Matvare":"Kålrot, kålrabi, norsk, rå","Kilokalorier":35,"Fett":0.1,"Karbohydrat":6.4,"Protein":0.9,"Kategori":"Grønnsaker","underkategori":"Kål"},
{"Matvare":"Rosenkål, norsk, rå","Kilokalorier":52,"Fett":0.6,"Karbohydrat":4.4,"Protein":5.1,"Kategori":"Grønnsaker","underkategori":"Kål"},
{"Matvare":"Rødkål, rå","Kilokalorier":32,"Fett":0.3,"Karbohydrat":5,"Protein":1.1,"Kategori":"Grønnsaker","underkategori":"Kål"},
{"Matvare":"Spisskål, rå","Kilokalorier":18,"Fett":0.3,"Karbohydrat":0.9,"Protein":2.1,"Kategori":"Grønnsaker","underkategori":"Kål"},
{"Matvare":"Surkål, kjøpt","Kilokalorier":29,"Fett":0,"Karbohydrat":5.1,"Protein":1.4,"Kategori":"Grønnsaker","underkategori":"Kål"},
{"Matvare":"Hvitløk, rå","Kilokalorier":106,"Fett":0.6,"Karbohydrat":16.3,"Protein":7.9,"Kategori":"Grønnsaker","underkategori":"Løk"},
{"Matvare":"Løk, gul/rød, norsk, rå","Kilokalorier":32,"Fett":0.1,"Karbohydrat":5.7,"Protein":1.1,"Kategori":"Grønnsaker","underkategori":"Løk"},
{"Matvare":"Purreløk, norsk, rå","Kilokalorier":28,"Fett":0.2,"Karbohydrat":3.6,"Protein":1.6,"Kategori":"Grønnsaker","underkategori":"Løk"},
{"Matvare":"Sjalottløk, rå","Kilokalorier":24,"Fett":0.2,"Karbohydrat":3.3,"Protein":1.5,"Kategori":"Grønnsaker","underkategori":"Løk"},
{"Matvare":"Vårløk, rå","Kilokalorier":23,"Fett":0.2,"Karbohydrat":2.3,"Protein":1.8,"Kategori":"Grønnsaker","underkategori":"Løk"},
{"Matvare":"Gulrot, uspesifisert, rå","Kilokalorier":36,"Fett":0.1,"Karbohydrat":6.7,"Protein":0.7,"Kategori":"Grønnsaker","underkategori":"Rotgrønnsak"},
{"Matvare":"Ingefærrot, rå","Kilokalorier":50,"Fett":0.8,"Karbohydrat":8.1,"Protein":1.8,"Kategori":"Grønnsaker","underkategori":"Rotgrønnsak"},
{"Matvare":"Jordskokk, rå","Kilokalorier":65,"Fett":0.6,"Karbohydrat":11.5,"Protein":2.1,"Kategori":"Grønnsaker","underkategori":"Rotgrønnsak"},
{"Matvare":"Neper, norsk, rå","Kilokalorier":29,"Fett":0.3,"Karbohydrat":4.7,"Protein":0.9,"Kategori":"Grønnsaker","underkategori":"Rotgrønnsak"},
{"Matvare":"Okra, rå","Kilokalorier":28,"Fett":0.2,"Karbohydrat":3,"Protein":1.9,"Kategori":"Grønnsaker","underkategori":"Rotgrønnsak"},
{"Matvare":"Pepperrot, rå","Kilokalorier":96,"Fett":0.7,"Karbohydrat":11,"Protein":7.7,"Kategori":"Grønnsaker","underkategori":"Rotgrønnsak"},
{"Matvare":"Persillerot, norsk, rå","Kilokalorier":46,"Fett":0.3,"Karbohydrat":7.3,"Protein":1.7,"Kategori":"Grønnsaker","underkategori":"Rotgrønnsak"},
{"Matvare":"Pommes frites, fryst","Kilokalorier":153,"Fett":5.2,"Karbohydrat":22,"Protein":2.2,"Kategori":"Grønnsaker","underkategori":"Rotgrønnsak"},
{"Matvare":"Potet, lagringspotet, rå","Kilokalorier":80,"Fett":0.1,"Karbohydrat":17.1,"Protein":1.9,"Kategori":"Grønnsaker","underkategori":"Rotgrønnsak"},
{"Matvare":"Reddik, norsk, rå","Kilokalorier":16,"Fett":0.1,"Karbohydrat":2.5,"Protein":0.7,"Kategori":"Grønnsaker","underkategori":"Rotgrønnsak"},
{"Matvare":"Rødbete, norsk, rå","Kilokalorier":49,"Fett":0.2,"Karbohydrat":8.9,"Protein":1.6,"Kategori":"Grønnsaker","underkategori":"Rotgrønnsak"},
{"Matvare":"Rødbeter, syltede","Kilokalorier":59,"Fett":0.1,"Karbohydrat":12.5,"Protein":1.3,"Kategori":"Grønnsaker","underkategori":"Rotgrønnsak"},
{"Matvare":"Sellerirot, norsk, rå","Kilokalorier":27,"Fett":0.3,"Karbohydrat":2.8,"Protein":1.6,"Kategori":"Grønnsaker","underkategori":"Rotgrønnsak"},
{"Matvare":"Søtpotet, rå","Kilokalorier":80,"Fett":0,"Karbohydrat":16.8,"Protein":1.6,"Kategori":"Grønnsaker","underkategori":"Rotgrønnsak"},
{"Matvare":"Vannkastanje, rå","Kilokalorier":52,"Fett":0.2,"Karbohydrat":10.4,"Protein":1.4,"Kategori":"Grønnsaker","underkategori":"Rotgrønnsak"},
{"Matvare":"Feltsalat, rå","Kilokalorier":17,"Fett":0.2,"Karbohydrat":0.2,"Protein":2.6,"Kategori":"Grønnsaker","underkategori":"Salat"},
{"Matvare":"Isbergsalat, issalat, norsk, rå","Kilokalorier":12,"Fett":0.1,"Karbohydrat":1.5,"Protein":0.8,"Kategori":"Grønnsaker","underkategori":"Salat"},
{"Matvare":"Rapidsalat, norsk, rå","Kilokalorier":11,"Fett":0.2,"Karbohydrat":0.3,"Protein":1.4,"Kategori":"Grønnsaker","underkategori":"Salat"},
{"Matvare":"Romanosalat, rå","Kilokalorier":16,"Fett":0.2,"Karbohydrat":1.3,"Protein":1.4,"Kategori":"Grønnsaker","underkategori":"Salat"},
{"Matvare":"Ruccolasalat, rå","Kilokalorier":28,"Fett":0.7,"Karbohydrat":2,"Protein":2.6,"Kategori":"Grønnsaker","underkategori":"Salat"},
{"Matvare":"Sikorisalat, rå","Kilokalorier":15,"Fett":0.6,"Karbohydrat":0.9,"Protein":0.5,"Kategori":"Grønnsaker","underkategori":"Salat"},
{"Matvare":"Spinat, rå","Kilokalorier":22,"Fett":0.4,"Karbohydrat":0.3,"Protein":3.3,"Kategori":"Grønnsaker","underkategori":"Salat"},
{"Matvare":"Kantarell, rå","Kilokalorier":17,"Fett":0.5,"Karbohydrat":0.4,"Protein":1.8,"Kategori":"Grønnsaker","underkategori":"Sopp"},
{"Matvare":"Sjampinjong, norsk,  rå","Kilokalorier":22,"Fett":0.3,"Karbohydrat":0.3,"Protein":3.6,"Kategori":"Grønnsaker","underkategori":"Sopp"},
{"Matvare":"Steinsopp, rå","Kilokalorier":30,"Fett":0.2,"Karbohydrat":2.4,"Protein":3.1,"Kategori":"Grønnsaker","underkategori":"Sopp"},
{"Matvare":"Østerssopp, rå","Kilokalorier":26,"Fett":0.3,"Karbohydrat":2.6,"Protein":2,"Kategori":"Grønnsaker","underkategori":"Sopp"},
{"Matvare":"Agurk, norsk, rå","Kilokalorier":10,"Fett":0.1,"Karbohydrat":1.2,"Protein":0.8,"Kategori":"Grønnsaker","underkategori":"Tomat/agurk/paprika"},
{"Matvare":"Agurker, syltede","Kilokalorier":37,"Fett":0.7,"Karbohydrat":6.1,"Protein":0.7,"Kategori":"Grønnsaker","underkategori":"Tomat/agurk/paprika"},
{"Matvare":"Cherrytomat, importert, rå","Kilokalorier":17,"Fett":0.2,"Karbohydrat":2.5,"Protein":0.6,"Kategori":"Grønnsaker","underkategori":"Tomat/agurk/paprika"},
{"Matvare":"Paprika, grønn, rå","Kilokalorier":21,"Fett":0.3,"Karbohydrat":2.8,"Protein":0.8,"Kategori":"Grønnsaker","underkategori":"Tomat/agurk/paprika"},
{"Matvare":"Paprika, gul/oransje, rå","Kilokalorier":26,"Fett":0.2,"Karbohydrat":5,"Protein":0.5,"Kategori":"Grønnsaker","underkategori":"Tomat/agurk/paprika"},
{"Matvare":"Paprika, rød, rå","Kilokalorier":26,"Fett":0.2,"Karbohydrat":4.2,"Protein":0.8,"Kategori":"Grønnsaker","underkategori":"Tomat/agurk/paprika"},
{"Matvare":"Tomat, hermetisk","Kilokalorier":20,"Fett":0.2,"Karbohydrat":3.3,"Protein":0.8,"Kategori":"Grønnsaker","underkategori":"Tomat/agurk/paprika"},
{"Matvare":"Tomat, norsk, rå","Kilokalorier":18,"Fett":0.2,"Karbohydrat":2.5,"Protein":0.7,"Kategori":"Grønnsaker","underkategori":"Tomat/agurk/paprika"},
{"Matvare":"Tomater, soltørkede, tørr","Kilokalorier":280,"Fett":3,"Karbohydrat":43,"Protein":14.1,"Kategori":"Grønnsaker","underkategori":"Tomat/agurk/paprika"},
{"Matvare":"Blodpudding","Kilokalorier":369,"Fett":20.4,"Karbohydrat":30.5,"Protein":14.2,"Kategori":"Kjøtt","underkategori":"bearbeidet/div"},
{"Matvare":"Hamburger, rå","Kilokalorier":167,"Fett":11.2,"Karbohydrat":0,"Protein":16.6,"Kategori":"Kjøtt","underkategori":"bearbeidet/div"},
{"Matvare":"Hjerte, rå","Kilokalorier":107,"Fett":3.9,"Karbohydrat":0,"Protein":18,"Kategori":"Kjøtt","underkategori":"bearbeidet/div"},
{"Matvare":"Karbonadedeig, rå","Kilokalorier":103,"Fett":2.2,"Karbohydrat":0,"Protein":20.9,"Kategori":"Kjøtt","underkategori":"bearbeidet/div"},
{"Matvare":"Kjøttdeig, kylling, rå","Kilokalorier":145,"Fett":8.1,"Karbohydrat":0,"Protein":18,"Kategori":"Kjøtt","underkategori":"bearbeidet/div"},
{"Matvare":"Kjøttdeig, storfe, uten salt og vann, rå","Kilokalorier":196,"Fett":13.2,"Karbohydrat":0,"Protein":19.4,"Kategori":"Kjøtt","underkategori":"bearbeidet/div"},
{"Matvare":"Kjøttfarse, rå","Kilokalorier":165,"Fett":11.2,"Karbohydrat":5,"Protein":11,"Kategori":"Kjøtt","underkategori":"bearbeidet/div"},
{"Matvare":"Medisterdeig, rå","Kilokalorier":206,"Fett":15.5,"Karbohydrat":0,"Protein":16.7,"Kategori":"Kjøtt","underkategori":"bearbeidet/div"},
{"Matvare":"Pinnekjøtt, råvare","Kilokalorier":452,"Fett":37,"Karbohydrat":0,"Protein":29.8,"Kategori":"Kjøtt","underkategori":"bearbeidet/div"},
{"Matvare":"Wienersnitzel, rå","Kilokalorier":244,"Fett":15.8,"Karbohydrat":5.8,"Protein":19.7,"Kategori":"Kjøtt","underkategori":"bearbeidet/div"},
{"Matvare":"And, kjøtt med skinn, rå","Kilokalorier":388,"Fett":37.3,"Karbohydrat":0,"Protein":13.1,"Kategori":"Kjøtt","underkategori":"Fugl"},
{"Matvare":"Gås, kjøtt med skinn, rå","Kilokalorier":366,"Fett":33.6,"Karbohydrat":0,"Protein":15.9,"Kategori":"Kjøtt","underkategori":"Fugl"},
{"Matvare":"Kalkun, bryst, filet, uten skinn, rå","Kilokalorier":114,"Fett":1.4,"Karbohydrat":0,"Protein":25.3,"Kategori":"Kjøtt","underkategori":"Fugl"},
{"Matvare":"Kalkun, kjøtt med skinn, rå","Kilokalorier":133,"Fett":5.2,"Karbohydrat":0,"Protein":21.6,"Kategori":"Kjøtt","underkategori":"Fugl"},
{"Matvare":"Kylling, filet, uten skinn, rå","Kilokalorier":111,"Fett":2.1,"Karbohydrat":0,"Protein":23,"Kategori":"Kjøtt","underkategori":"Fugl"},
{"Matvare":"Kylling, hel, med skinn, rå","Kilokalorier":165,"Fett":10.2,"Karbohydrat":0,"Protein":18.2,"Kategori":"Kjøtt","underkategori":"Fugl"},
{"Matvare":"Kylling, hel, uten skinn, rå","Kilokalorier":107,"Fett":3,"Karbohydrat":0,"Protein":20,"Kategori":"Kjøtt","underkategori":"Fugl"},
{"Matvare":"Kylling, lår (overlår og lårklubbe), med skinn, rå","Kilokalorier":171,"Fett":11.5,"Karbohydrat":0,"Protein":16.9,"Kategori":"Kjøtt","underkategori":"Fugl"},
{"Matvare":"Lever, kylling, rå","Kilokalorier":113,"Fett":4.1,"Karbohydrat":0,"Protein":19.1,"Kategori":"Kjøtt","underkategori":"Fugl"},
{"Matvare":"Rype, bryst, uten skinn, rå","Kilokalorier":122,"Fett":4.5,"Karbohydrat":0,"Protein":20.3,"Kategori":"Kjøtt","underkategori":"Fugl"},
{"Matvare":"Lam, bogstek, rå","Kilokalorier":187,"Fett":12.6,"Karbohydrat":0,"Protein":18.5,"Kategori":"Kjøtt","underkategori":"Lam/sau"},
{"Matvare":"Lam, flatbiff, rå","Kilokalorier":104,"Fett":2.1,"Karbohydrat":0,"Protein":21.3,"Kategori":"Kjøtt","underkategori":"Lam/sau"},
{"Matvare":"Lam, fårikålkjøtt, rå","Kilokalorier":230,"Fett":17.7,"Karbohydrat":0,"Protein":17.6,"Kategori":"Kjøtt","underkategori":"Lam/sau"},
{"Matvare":"Lam, grytekjøtt, rå","Kilokalorier":192,"Fett":13.2,"Karbohydrat":0,"Protein":18.4,"Kategori":"Kjøtt","underkategori":"Lam/sau"},
{"Matvare":"Lam, indrefilet, rå","Kilokalorier":116,"Fett":3.8,"Karbohydrat":0,"Protein":20.4,"Kategori":"Kjøtt","underkategori":"Lam/sau"},
{"Matvare":"Lam, kotelett og sadel, kjøtt med fettrand, rå","Kilokalorier":257,"Fett":20.4,"Karbohydrat":0,"Protein":18.3,"Kategori":"Kjøtt","underkategori":"Lam/sau"},
{"Matvare":"Lam, lår med mørbrad, rå","Kilokalorier":181,"Fett":11.6,"Karbohydrat":0,"Protein":19.1,"Kategori":"Kjøtt","underkategori":"Lam/sau"},
{"Matvare":"Lam, ribbe, side med ben, rå","Kilokalorier":285,"Fett":24.2,"Karbohydrat":0,"Protein":16.8,"Kategori":"Kjøtt","underkategori":"Lam/sau"},
{"Matvare":"Lam, sadel, rå","Kilokalorier":227,"Fett":17.1,"Karbohydrat":0,"Protein":18.3,"Kategori":"Kjøtt","underkategori":"Lam/sau"},
{"Matvare":"Lam, ytrefilet, rå","Kilokalorier":120,"Fett":3.9,"Karbohydrat":0,"Protein":21.3,"Kategori":"Kjøtt","underkategori":"Lam/sau"},
{"Matvare":"Lever, lam, rå","Kilokalorier":128,"Fett":4.1,"Karbohydrat":2,"Protein":20.7,"Kategori":"Kjøtt","underkategori":"Lam/sau"},
{"Matvare":"Sau, fårekjøtt, lettsaltet, rå","Kilokalorier":371,"Fett":35,"Karbohydrat":0,"Protein":14,"Kategori":"Kjøtt","underkategori":"Lam/sau"},
{"Matvare":"Grillpølse","Kilokalorier":261,"Fett":21.4,"Karbohydrat":5.5,"Protein":11.5,"Kategori":"Kjøtt","underkategori":"Pølse"},
{"Matvare":"Kylling- og kalkunpølse, med mindre fett","Kilokalorier":168,"Fett":10.6,"Karbohydrat":5,"Protein":13.1,"Kategori":"Kjøtt","underkategori":"Pølse"},
{"Matvare":"Kylling- og kalkunpølse, med ost","Kilokalorier":201,"Fett":14.1,"Karbohydrat":4.6,"Protein":13.4,"Kategori":"Kjøtt","underkategori":"Pølse"},
{"Matvare":"Salsiccia, italiensk pølse","Kilokalorier":271,"Fett":18.3,"Karbohydrat":4.7,"Protein":21.8,"Kategori":"Kjøtt","underkategori":"Pølse"},
{"Matvare":"Wienerpølse","Kilokalorier":256,"Fett":21.2,"Karbohydrat":5.4,"Protein":10.9,"Kategori":"Kjøtt","underkategori":"Pølse"},
{"Matvare":"Wienerpølse, med mindre fett","Kilokalorier":160,"Fett":10.7,"Karbohydrat":5.8,"Protein":10.1,"Kategori":"Kjøtt","underkategori":"Pølse"},
{"Matvare":"Bankekjøtt, salt","Kilokalorier":102,"Fett":4.3,"Karbohydrat":0,"Protein":15.9,"Kategori":"Kjøtt","underkategori":"Storfe"},
{"Matvare":"Kalv, koteletter, rå","Kilokalorier":117,"Fett":3,"Karbohydrat":0,"Protein":22.5,"Kategori":"Kjøtt","underkategori":"Storfe"},
{"Matvare":"Kalv, stek, rå","Kilokalorier":107,"Fett":2.4,"Karbohydrat":0,"Protein":21.4,"Kategori":"Kjøtt","underkategori":"Storfe"},
{"Matvare":"Lever, storfe, rå","Kilokalorier":124,"Fett":3.2,"Karbohydrat":3.5,"Protein":20.3,"Kategori":"Kjøtt","underkategori":"Storfe"},
{"Matvare":"Storfe, bankekjøtt, rå","Kilokalorier":124,"Fett":4.1,"Karbohydrat":0,"Protein":21.9,"Kategori":"Kjøtt","underkategori":"Storfe"},
{"Matvare":"Storfe, bibringe, rå","Kilokalorier":209,"Fett":14.8,"Karbohydrat":0,"Protein":18.9,"Kategori":"Kjøtt","underkategori":"Storfe"},
{"Matvare":"Storfe, bog, uten knoke, rå","Kilokalorier":160,"Fett":8.8,"Karbohydrat":0,"Protein":20.2,"Kategori":"Kjøtt","underkategori":"Storfe"},
{"Matvare":"Storfe, bogstek, rå","Kilokalorier":120,"Fett":3.7,"Karbohydrat":0,"Protein":21.8,"Kategori":"Kjøtt","underkategori":"Storfe"},
{"Matvare":"Storfe, entrecôte, synlig fett skåret vekk, rå","Kilokalorier":141,"Fett":5.7,"Karbohydrat":0,"Protein":22.4,"Kategori":"Kjøtt","underkategori":"Storfe"},
{"Matvare":"Storfe, entrecôtekam, rå","Kilokalorier":200,"Fett":13.1,"Karbohydrat":0,"Protein":20.5,"Kategori":"Kjøtt","underkategori":"Storfe"},
{"Matvare":"Storfe, fett fra storfekjøtt, rå","Kilokalorier":732,"Fett":80,"Karbohydrat":0,"Protein":3,"Kategori":"Kjøtt","underkategori":"Storfe"},
{"Matvare":"Storfe, filetkam, rå","Kilokalorier":165,"Fett":9,"Karbohydrat":0,"Protein":21.1,"Kategori":"Kjøtt","underkategori":"Storfe"},
{"Matvare":"Storfe, flatbiff, rå","Kilokalorier":105,"Fett":1.7,"Karbohydrat":0,"Protein":22.5,"Kategori":"Kjøtt","underkategori":"Storfe"},
{"Matvare":"Storfe, høyrygg, rå","Kilokalorier":162,"Fett":9.2,"Karbohydrat":0,"Protein":19.9,"Kategori":"Kjøtt","underkategori":"Storfe"},
{"Matvare":"Storfe, indrefilet, rå","Kilokalorier":118,"Fett":3.7,"Karbohydrat":0,"Protein":21.2,"Kategori":"Kjøtt","underkategori":"Storfe"},
{"Matvare":"Storfe, kam, rå","Kilokalorier":162,"Fett":8.6,"Karbohydrat":0,"Protein":21.1,"Kategori":"Kjøtt","underkategori":"Storfe"},
{"Matvare":"Storfe, kotelettkam, rå","Kilokalorier":170,"Fett":9.9,"Karbohydrat":0,"Protein":20.2,"Kategori":"Kjøtt","underkategori":"Storfe"},
{"Matvare":"Storfe, mørbrad, rå","Kilokalorier":109,"Fett":2.3,"Karbohydrat":0,"Protein":22.2,"Kategori":"Kjøtt","underkategori":"Storfe"},
{"Matvare":"Storfe, rundstek, rå","Kilokalorier":107,"Fett":2,"Karbohydrat":0,"Protein":22.2,"Kategori":"Kjøtt","underkategori":"Storfe"},
{"Matvare":"Storfe, ytrefilet, rå","Kilokalorier":109,"Fett":2.3,"Karbohydrat":0,"Protein":22.2,"Kategori":"Kjøtt","underkategori":"Storfe"},
{"Matvare":"Kjøttdeig, svin, rå","Kilokalorier":144,"Fett":6.7,"Karbohydrat":0,"Protein":21,"Kategori":"Kjøtt","underkategori":"Svin"},
{"Matvare":"Lever, svin, rå","Kilokalorier":120,"Fett":3.4,"Karbohydrat":0.8,"Protein":21.4,"Kategori":"Kjøtt","underkategori":"Svin"},
{"Matvare":"Svin, bacon med svor, rå","Kilokalorier":339,"Fett":31.5,"Karbohydrat":0,"Protein":13.9,"Kategori":"Kjøtt","underkategori":"Svin"},
{"Matvare":"Svin, bogstek, kjøtt uten fettrand, rå","Kilokalorier":144,"Fett":6.7,"Karbohydrat":0,"Protein":21,"Kategori":"Kjøtt","underkategori":"Svin"},
{"Matvare":"Svin, bogstek, med fettrand, rå","Kilokalorier":220,"Fett":16.1,"Karbohydrat":0,"Protein":18.7,"Kategori":"Kjøtt","underkategori":"Svin"},
{"Matvare":"Svin, familieribbe, rå","Kilokalorier":328,"Fett":29.5,"Karbohydrat":0,"Protein":15.6,"Kategori":"Kjøtt","underkategori":"Svin"},
{"Matvare":"Svin, flatbiff, rå","Kilokalorier":103,"Fett":1.7,"Karbohydrat":0,"Protein":22,"Kategori":"Kjøtt","underkategori":"Svin"},
{"Matvare":"Svin, grillben, rå","Kilokalorier":247,"Fett":19.9,"Karbohydrat":0,"Protein":17,"Kategori":"Kjøtt","underkategori":"Svin"},
{"Matvare":"Svin, indrefilet, rå","Kilokalorier":116,"Fett":3.1,"Karbohydrat":0,"Protein":22,"Kategori":"Kjøtt","underkategori":"Svin"},
{"Matvare":"Svin, kjøtt fra knoke, rå","Kilokalorier":151,"Fett":8.1,"Karbohydrat":0,"Protein":19.5,"Kategori":"Kjøtt","underkategori":"Svin"},
{"Matvare":"Svin, kotelett, kam, svinekoteletter, inntil 5 mm fettrand, rå","Kilokalorier":243,"Fett":18.3,"Karbohydrat":0,"Protein":19.8,"Kategori":"Kjøtt","underkategori":"Svin"},
{"Matvare":"Svin, midtribbe, med kam og svor, rå","Kilokalorier":328,"Fett":29.5,"Karbohydrat":0,"Protein":15.6,"Kategori":"Kjøtt","underkategori":"Svin"},
{"Matvare":"Svin, mørbrad, rå","Kilokalorier":215,"Fett":15.7,"Karbohydrat":0,"Protein":18.5,"Kategori":"Kjøtt","underkategori":"Svin"},
{"Matvare":"Svin, nakkekoteletter, rå","Kilokalorier":225,"Fett":17,"Karbohydrat":0,"Protein":18,"Kategori":"Kjøtt","underkategori":"Svin"},
{"Matvare":"Svin, sideflesk, lettsaltet, rå","Kilokalorier":301,"Fett":27.4,"Karbohydrat":0,"Protein":13.6,"Kategori":"Kjøtt","underkategori":"Svin"},
{"Matvare":"Svin, sideflesk, uten ben, rå","Kilokalorier":384,"Fett":36.6,"Karbohydrat":0,"Protein":13.6,"Kategori":"Kjøtt","underkategori":"Svin"},
{"Matvare":"Svin, skinke, med knoke, rå","Kilokalorier":219,"Fett":16.4,"Karbohydrat":0,"Protein":17.9,"Kategori":"Kjøtt","underkategori":"Svin"},
{"Matvare":"Svin, skinkestek med fettrand, uten svor, rå","Kilokalorier":221,"Fett":16,"Karbohydrat":0,"Protein":19.2,"Kategori":"Kjøtt","underkategori":"Svin"},
{"Matvare":"Svin, skinkestek, rå","Kilokalorier":130,"Fett":4.7,"Karbohydrat":0,"Protein":22,"Kategori":"Kjøtt","underkategori":"Svin"},
{"Matvare":"Svin, tynnribbe, med svor, rå","Kilokalorier":371,"Fett":35.1,"Karbohydrat":0,"Protein":13.8,"Kategori":"Kjøtt","underkategori":"Svin"},
{"Matvare":"Svin, ytrefilet, rå","Kilokalorier":110,"Fett":1.6,"Karbohydrat":0,"Protein":24,"Kategori":"Kjøtt","underkategori":"Svin"},
{"Matvare":"Svinekam, røkt","Kilokalorier":209,"Fett":17.6,"Karbohydrat":0.3,"Protein":12.3,"Kategori":"Kjøtt","underkategori":"Svin"},
{"Matvare":"Hare, kjøtt, rå","Kilokalorier":129,"Fett":5,"Karbohydrat":0,"Protein":21.1,"Kategori":"Kjøtt","underkategori":"Vilt"},
{"Matvare":"Hjort, stek, rå","Kilokalorier":98,"Fett":1.3,"Karbohydrat":0,"Protein":21.7,"Kategori":"Kjøtt","underkategori":"Vilt"},
{"Matvare":"Kanin, kjøtt, rå","Kilokalorier":124,"Fett":4,"Karbohydrat":0,"Protein":22,"Kategori":"Kjøtt","underkategori":"Vilt"},
{"Matvare":"Lever, rein, rå","Kilokalorier":128,"Fett":4.1,"Karbohydrat":3.3,"Protein":19.5,"Kategori":"Kjøtt","underkategori":"Vilt"},
{"Matvare":"Reinsdyr, bog, stek, rå","Kilokalorier":118,"Fett":3.6,"Karbohydrat":0,"Protein":21.3,"Kategori":"Kjøtt","underkategori":"Vilt"},
{"Matvare":"Reinsdyr, kjøtt, tørket, rå","Kilokalorier":318,"Fett":17.6,"Karbohydrat":0,"Protein":40,"Kategori":"Kjøtt","underkategori":"Vilt"},
{"Matvare":"Reinsdyrskav, fryst, rå","Kilokalorier":145,"Fett":7.5,"Karbohydrat":0,"Protein":19.3,"Kategori":"Kjøtt","underkategori":"Vilt"},
{"Matvare":"Rådyr, kjøtt, rå","Kilokalorier":95,"Fett":1.2,"Karbohydrat":0,"Protein":21,"Kategori":"Kjøtt","underkategori":"Vilt"},
{"Matvare":"Villsvin, kjøtt, rå","Kilokalorier":105,"Fett":1.5,"Karbohydrat":0,"Protein":23,"Kategori":"Kjøtt","underkategori":"Vilt"},
{"Matvare":"Bokhvete, hele korn","Kilokalorier":335,"Fett":2,"Karbohydrat":65.3,"Protein":11.1,"Kategori":"Korn/nøtter","underkategori":"Korn"},
{"Matvare":"Bokhvetemel, lyst","Kilokalorier":353,"Fett":3.6,"Karbohydrat":65.1,"Protein":13.5,"Kategori":"Korn/nøtter","underkategori":"Korn"},
{"Matvare":"Bulgurgryn, tørr","Kilokalorier":327,"Fett":2.3,"Karbohydrat":61.9,"Protein":10.8,"Kategori":"Korn/nøtter","underkategori":"Korn"},
{"Matvare":"Byggmel","Kilokalorier":302,"Fett":1.1,"Karbohydrat":60.6,"Protein":8.6,"Kategori":"Korn/nøtter","underkategori":"Korn"},
{"Matvare":"Byggryn","Kilokalorier":327,"Fett":1.1,"Karbohydrat":65.4,"Protein":8.6,"Kategori":"Korn/nøtter","underkategori":"Korn"},
{"Matvare":"Corn flakes, Kelloggs","Kilokalorier":381,"Fett":1,"Karbohydrat":84.1,"Protein":7.1,"Kategori":"Korn/nøtter","underkategori":"Korn"},
{"Matvare":"Havregryn, lettkokte/store","Kilokalorier":389,"Fett":7.8,"Karbohydrat":63.1,"Protein":11.4,"Kategori":"Korn/nøtter","underkategori":"Korn"},
{"Matvare":"Havrekli","Kilokalorier":361,"Fett":7.5,"Karbohydrat":54.6,"Protein":12.3,"Kategori":"Korn/nøtter","underkategori":"Korn"},
{"Matvare":"Havremel","Kilokalorier":373,"Fett":7,"Karbohydrat":61.7,"Protein":11.7,"Kategori":"Korn/nøtter","underkategori":"Korn"},
{"Matvare":"Hvetekli","Kilokalorier":294,"Fett":5,"Karbohydrat":30.4,"Protein":16.6,"Kategori":"Korn/nøtter","underkategori":"Korn"},
{"Matvare":"Kornblanding,  4-korn","Kilokalorier":324,"Fett":3.2,"Karbohydrat":56.7,"Protein":10.6,"Kategori":"Korn/nøtter","underkategori":"Korn"},
{"Matvare":"Linfrø, knuste","Kilokalorier":513,"Fett":42.2,"Karbohydrat":1.6,"Protein":18.3,"Kategori":"Korn/nøtter","underkategori":"Korn"},
{"Matvare":"Semulegryn, hvetegryn","Kilokalorier":339,"Fett":2,"Karbohydrat":69,"Protein":10,"Kategori":"Korn/nøtter","underkategori":"Korn"},
{"Matvare":"Cashewnøtter","Kilokalorier":592,"Fett":43.8,"Karbohydrat":29.4,"Protein":18.2,"Kategori":"Korn/nøtter","underkategori":"Nøtter"},
{"Matvare":"Cashewnøtter, saltet","Kilokalorier":603,"Fett":48.7,"Karbohydrat":19.2,"Protein":18,"Kategori":"Korn/nøtter","underkategori":"Nøtter"},
{"Matvare":"Chilinøtter, Eldorado","Kilokalorier":522,"Fett":32,"Karbohydrat":40.3,"Protein":14.4,"Kategori":"Korn/nøtter","underkategori":"Nøtter"},
{"Matvare":"Hasselnøtter","Kilokalorier":645,"Fett":60.8,"Karbohydrat":4.8,"Protein":15,"Kategori":"Korn/nøtter","underkategori":"Nøtter"},
{"Matvare":"Macadamianøtter","Kilokalorier":753,"Fett":75.8,"Karbohydrat":5.6,"Protein":7.9,"Kategori":"Korn/nøtter","underkategori":"Nøtter"},
{"Matvare":"Mandler","Kilokalorier":577,"Fett":49.2,"Karbohydrat":6.3,"Protein":21.2,"Kategori":"Korn/nøtter","underkategori":"Nøtter"},
{"Matvare":"Paranøtter","Kilokalorier":680,"Fett":66.4,"Karbohydrat":2.6,"Protein":14.3,"Kategori":"Korn/nøtter","underkategori":"Nøtter"},
{"Matvare":"Pinjekjerner","Kilokalorier":697,"Fett":68.4,"Karbohydrat":5,"Protein":13.7,"Kategori":"Korn/nøtter","underkategori":"Nøtter"},
{"Matvare":"Valnøtter","Kilokalorier":672,"Fett":65.2,"Karbohydrat":2.7,"Protein":15.2,"Kategori":"Korn/nøtter","underkategori":"Nøtter"},
{"Matvare":"Geitmelk, langtidsholdbar","Kilokalorier":61,"Fett":3.6,"Karbohydrat":4,"Protein":3.1,"Kategori":"Meieriprodukt","underkategori":"Melk"},
{"Matvare":"Helmelk, uspesifisert","Kilokalorier":64,"Fett":3.6,"Karbohydrat":4.5,"Protein":3.4,"Kategori":"Meieriprodukt","underkategori":"Melk"},
{"Matvare":"Kaffefløte, 10 % fett","Kilokalorier":119,"Fett":10,"Karbohydrat":4.3,"Protein":3,"Kategori":"Meieriprodukt","underkategori":"Melk"},
{"Matvare":"Kaffemelk, 3,5 % fett","Kilokalorier":62,"Fett":3.5,"Karbohydrat":4.4,"Protein":3.3,"Kategori":"Meieriprodukt","underkategori":"Melk"},
{"Matvare":"Kremfløte, 38 % fett","Kilokalorier":362,"Fett":38,"Karbohydrat":2.9,"Protein":2.1,"Kategori":"Meieriprodukt","underkategori":"Melk"},
{"Matvare":"Lettmelk, 0,7 % fett, vitamin D","Kilokalorier":38,"Fett":0.7,"Karbohydrat":4.5,"Protein":3.5,"Kategori":"Meieriprodukt","underkategori":"Melk"},
{"Matvare":"Lettmelk, 1,0 % fett","Kilokalorier":41,"Fett":1,"Karbohydrat":4.6,"Protein":3.5,"Kategori":"Meieriprodukt","underkategori":"Melk"},
{"Matvare":"Matfløte, 20 % fett","Kilokalorier":206,"Fett":20,"Karbohydrat":3.9,"Protein":2.7,"Kategori":"Meieriprodukt","underkategori":"Melk"},
{"Matvare":"Skummet melk","Kilokalorier":33,"Fett":0.1,"Karbohydrat":4.5,"Protein":3.5,"Kategori":"Meieriprodukt","underkategori":"Melk"},
{"Matvare":"Syrnet melk, jordbær, Biola","Kilokalorier":52,"Fett":0.1,"Karbohydrat":9.7,"Protein":3.1,"Kategori":"Meieriprodukt","underkategori":"Melk"},
{"Matvare":"Syrnet melk, Kulturmjølk","Kilokalorier":61,"Fett":3.5,"Karbohydrat":4,"Protein":3.3,"Kategori":"Meieriprodukt","underkategori":"Melk"},
{"Matvare":"Syrnet melk, Skumma Kulturmjølk","Kilokalorier":33,"Fett":0.4,"Karbohydrat":4.1,"Protein":3.2,"Kategori":"Meieriprodukt","underkategori":"Melk"},
{"Matvare":"Cottage Cheese","Kilokalorier":97,"Fett":4.3,"Karbohydrat":1.5,"Protein":13,"Kategori":"Meieriprodukt","underkategori":"Rømme o.l."},
{"Matvare":"Crème Fraîche, 35 % fett","Kilokalorier":335,"Fett":35,"Karbohydrat":2.9,"Protein":2.2,"Kategori":"Meieriprodukt","underkategori":"Rømme o.l."},
{"Matvare":"Kvarg, 1 % fett, Kesam","Kilokalorier":66,"Fett":1,"Karbohydrat":4.3,"Protein":10,"Kategori":"Meieriprodukt","underkategori":"Rømme o.l."},
{"Matvare":"Kvarg, 7 % fett, Kesam","Kilokalorier":108,"Fett":7.1,"Karbohydrat":4,"Protein":7,"Kategori":"Meieriprodukt","underkategori":"Rømme o.l."},
{"Matvare":"Lettrømme, 10 % fett","Kilokalorier":119,"Fett":10,"Karbohydrat":4.1,"Protein":3.1,"Kategori":"Meieriprodukt","underkategori":"Rømme o.l."},
{"Matvare":"Lettrømme, 18 % fett","Kilokalorier":188,"Fett":18,"Karbohydrat":3.7,"Protein":2.8,"Kategori":"Meieriprodukt","underkategori":"Rømme o.l."},
{"Matvare":"Seterrømme, 35 % fett","Kilokalorier":335,"Fett":35,"Karbohydrat":2.9,"Protein":2.2,"Kategori":"Meieriprodukt","underkategori":"Rømme o.l."},
{"Matvare":"Skyr, naturell","Kilokalorier":74,"Fett":1,"Karbohydrat":4.3,"Protein":12,"Kategori":"Meieriprodukt","underkategori":"Rømme o.l."},
{"Matvare":"Yoghurt, frukt, 0,1 % fett, lett, Yoplait","Kilokalorier":52,"Fett":0.1,"Karbohydrat":8.9,"Protein":3.9,"Kategori":"Meieriprodukt","underkategori":"Rømme o.l."},
{"Matvare":"Yoghurt, jordbær","Kilokalorier":88,"Fett":3,"Karbohydrat":11.5,"Protein":3.7,"Kategori":"Meieriprodukt","underkategori":"Rømme o.l."},
{"Matvare":"Ansjos, hermetisk","Kilokalorier":216,"Fett":13.1,"Karbohydrat":12.1,"Protein":12.5,"Kategori":"Pålegg","underkategori":"Fisk"},
{"Matvare":"Brisling, i olje, avrent, hermetisk","Kilokalorier":261,"Fett":20.9,"Karbohydrat":0,"Protein":18.3,"Kategori":"Pålegg","underkategori":"Fisk"},
{"Matvare":"Brisling, i tomat, hermetisk","Kilokalorier":203,"Fett":14.7,"Karbohydrat":2.7,"Protein":15,"Kategori":"Pålegg","underkategori":"Fisk"},
{"Matvare":"Gaffelbiter, sild, hermetisk","Kilokalorier":240,"Fett":16,"Karbohydrat":8,"Protein":16,"Kategori":"Pålegg","underkategori":"Fisk"},
{"Matvare":"Kaviarmix","Kilokalorier":542,"Fett":53.1,"Karbohydrat":9.2,"Protein":6.8,"Kategori":"Pålegg","underkategori":"Fisk"},
{"Matvare":"Laks, filet, gravet","Kilokalorier":179,"Fett":9.2,"Karbohydrat":2.8,"Protein":21.2,"Kategori":"Pålegg","underkategori":"Fisk"},
{"Matvare":"Makrellfilet, i tomat, 60 % makrell, hermetisk","Kilokalorier":241,"Fett":19.4,"Karbohydrat":3.9,"Protein":11.9,"Kategori":"Pålegg","underkategori":"Fisk"},
{"Matvare":"Chorizo, pølse","Kilokalorier":360,"Fett":29.1,"Karbohydrat":3.4,"Protein":20.7,"Kategori":"Pålegg","underkategori":"Kjøtt"},
{"Matvare":"Fårepølse","Kilokalorier":339,"Fett":27.1,"Karbohydrat":0.5,"Protein":23.3,"Kategori":"Pålegg","underkategori":"Kjøtt"},
{"Matvare":"Kalverull","Kilokalorier":144,"Fett":8.2,"Karbohydrat":2,"Protein":15.4,"Kategori":"Pålegg","underkategori":"Kjøtt"},
{"Matvare":"Kokt skinke, First Price","Kilokalorier":104,"Fett":4,"Karbohydrat":0.9,"Protein":16,"Kategori":"Pålegg","underkategori":"Kjøtt"},
{"Matvare":"Kyllingpostei","Kilokalorier":134,"Fett":7.8,"Karbohydrat":5.8,"Protein":10.1,"Kategori":"Pålegg","underkategori":"Kjøtt"},
{"Matvare":"Lammerull","Kilokalorier":251,"Fett":20.3,"Karbohydrat":0.2,"Protein":16.8,"Kategori":"Pålegg","underkategori":"Kjøtt"},
{"Matvare":"Leverpostei, hermetisk, Stabburet","Kilokalorier":237,"Fett":20,"Karbohydrat":4.3,"Protein":9.9,"Kategori":"Pålegg","underkategori":"Kjøtt"},
{"Matvare":"Morrpølse","Kilokalorier":417,"Fett":34.5,"Karbohydrat":0.1,"Protein":26.5,"Kategori":"Pålegg","underkategori":"Kjøtt"},
{"Matvare":"Okserull","Kilokalorier":166,"Fett":8.7,"Karbohydrat":0.5,"Protein":21.4,"Kategori":"Pålegg","underkategori":"Kjøtt"},
{"Matvare":"Reinsdyrpølse","Kilokalorier":426,"Fett":38.5,"Karbohydrat":0,"Protein":20,"Kategori":"Pålegg","underkategori":"Kjøtt"},
{"Matvare":"Ribberull, skiver","Kilokalorier":193,"Fett":13.5,"Karbohydrat":0,"Protein":18,"Kategori":"Pålegg","underkategori":"Kjøtt"},
{"Matvare":"Roastbiff, skiver","Kilokalorier":129,"Fett":2.7,"Karbohydrat":0,"Protein":26.1,"Kategori":"Pålegg","underkategori":"Kjøtt"},
{"Matvare":"Salami","Kilokalorier":429,"Fett":39.5,"Karbohydrat":0.9,"Protein":17.6,"Kategori":"Pålegg","underkategori":"Kjøtt"},
{"Matvare":"Servelat","Kilokalorier":198,"Fett":14.5,"Karbohydrat":7.1,"Protein":9.9,"Kategori":"Pålegg","underkategori":"Kjøtt"},
{"Matvare":"Servelat, mager, Gilde","Kilokalorier":145,"Fett":9,"Karbohydrat":4.5,"Protein":11.4,"Kategori":"Pålegg","underkategori":"Kjøtt"},
{"Matvare":"Skinkerull, Westfalerskinke","Kilokalorier":286,"Fett":20,"Karbohydrat":0,"Protein":26.6,"Kategori":"Pålegg","underkategori":"Kjøtt"},
{"Matvare":"Spekeskinke","Kilokalorier":203,"Fett":9.2,"Karbohydrat":0,"Protein":30,"Kategori":"Pålegg","underkategori":"Kjøtt"},
{"Matvare":"Sylte","Kilokalorier":304,"Fett":23.2,"Karbohydrat":0.3,"Protein":23.6,"Kategori":"Pålegg","underkategori":"Kjøtt"},
{"Matvare":"Gorgonzola, blåmuggost","Kilokalorier":359,"Fett":31.2,"Karbohydrat":0.1,"Protein":19.4,"Kategori":"Pålegg","underkategori":"Ost – blåmugg"},
{"Matvare":"Normanna, blåmuggost","Kilokalorier":336,"Fett":28,"Karbohydrat":0,"Protein":21,"Kategori":"Pålegg","underkategori":"Ost – blåmugg"},
{"Matvare":"Norzola, blåmuggost","Kilokalorier":383,"Fett":35,"Karbohydrat":0,"Protein":17,"Kategori":"Pålegg","underkategori":"Ost – blåmugg"},
{"Matvare":"Roquefort, blåmuggost","Kilokalorier":355,"Fett":31,"Karbohydrat":0,"Protein":19,"Kategori":"Pålegg","underkategori":"Ost – blåmugg"},
{"Matvare":"Royal Blue, blåmuggost","Kilokalorier":452,"Fett":44,"Karbohydrat":0,"Protein":14,"Kategori":"Pålegg","underkategori":"Ost – blåmugg"},
{"Matvare":"Selbu blå, blåmuggost","Kilokalorier":420,"Fett":40,"Karbohydrat":0,"Protein":15,"Kategori":"Pålegg","underkategori":"Ost – blåmugg"},
{"Matvare":"Stilton, blåmuggost","Kilokalorier":410,"Fett":35,"Karbohydrat":0.1,"Protein":23.7,"Kategori":"Pålegg","underkategori":"Ost – blåmugg"},
{"Matvare":"Brunost, uspesifisert","Kilokalorier":437,"Fett":26.2,"Karbohydrat":39.7,"Protein":10.6,"Kategori":"Pålegg","underkategori":"Ost-brun"},
{"Matvare":"Fløtemysost, brunost","Kilokalorier":422,"Fett":26,"Karbohydrat":36,"Protein":11,"Kategori":"Pålegg","underkategori":"Ost-brun"},
{"Matvare":"Fløtemysost, brunost, lettere","Kilokalorier":368,"Fett":16,"Karbohydrat":44,"Protein":12,"Kategori":"Pålegg","underkategori":"Ost-brun"},
{"Matvare":"Geitost, brunost","Kilokalorier":439,"Fett":27,"Karbohydrat":36,"Protein":13,"Kategori":"Pålegg","underkategori":"Ost-brun"},
{"Matvare":"Gudbrandsdalsost, brunost","Kilokalorier":436,"Fett":28,"Karbohydrat":35,"Protein":11,"Kategori":"Pålegg","underkategori":"Ost-brun"},
{"Matvare":"Gudbrandsdalsost, brunost, lettere","Kilokalorier":364,"Fett":16,"Karbohydrat":43,"Protein":12,"Kategori":"Pålegg","underkategori":"Ost-brun"},
{"Matvare":"Cheddar, gulost","Kilokalorier":416,"Fett":34.9,"Karbohydrat":0.1,"Protein":25.4,"Kategori":"Pålegg","underkategori":"Ost-gul"},
{"Matvare":"Edamer, gulost","Kilokalorier":355,"Fett":27,"Karbohydrat":0,"Protein":28,"Kategori":"Pålegg","underkategori":"Ost-gul"},
{"Matvare":"Feta, ost med geitmelk","Kilokalorier":250,"Fett":20.2,"Karbohydrat":1.5,"Protein":15.6,"Kategori":"Pålegg","underkategori":"Ost-gul"},
{"Matvare":"Gamalost","Kilokalorier":221,"Fett":0.6,"Karbohydrat":0,"Protein":54,"Kategori":"Pålegg","underkategori":"Ost-gul"},
{"Matvare":"Gulost, uspesifisert","Kilokalorier":348,"Fett":26.7,"Karbohydrat":0,"Protein":27,"Kategori":"Pålegg","underkategori":"Ost-gul"},
{"Matvare":"Halloumi, ost","Kilokalorier":290,"Fett":21.9,"Karbohydrat":0.9,"Protein":22.3,"Kategori":"Pålegg","underkategori":"Ost-gul"},
{"Matvare":"Jarlsberg, gulost","Kilokalorier":351,"Fett":27,"Karbohydrat":0,"Protein":27,"Kategori":"Pålegg","underkategori":"Ost-gul"},
{"Matvare":"Norvegia, gulost, fyldig","Kilokalorier":370,"Fett":30,"Karbohydrat":0,"Protein":25,"Kategori":"Pålegg","underkategori":"Ost-gul"},
{"Matvare":"Norvegia, gulost, lettere","Kilokalorier":268,"Fett":16,"Karbohydrat":0,"Protein":31,"Kategori":"Pålegg","underkategori":"Ost-gul"},
{"Matvare":"Norvegia, gulost, vellagret","Kilokalorier":360,"Fett":28,"Karbohydrat":0,"Protein":27,"Kategori":"Pålegg","underkategori":"Ost-gul"},
{"Matvare":"Nøkkelost","Kilokalorier":351,"Fett":27,"Karbohydrat":0,"Protein":27,"Kategori":"Pålegg","underkategori":"Ost-gul"},
{"Matvare":"Nøkkelost, lettere","Kilokalorier":272,"Fett":16,"Karbohydrat":0,"Protein":32,"Kategori":"Pålegg","underkategori":"Ost-gul"},
{"Matvare":"Parmesan, ost","Kilokalorier":416,"Fett":29.7,"Karbohydrat":0.9,"Protein":36.2,"Kategori":"Pålegg","underkategori":"Ost-gul"},
{"Matvare":"Port Salut, kittmodnet ost","Kilokalorier":321,"Fett":25,"Karbohydrat":0,"Protein":24,"Kategori":"Pålegg","underkategori":"Ost-gul"},
{"Matvare":"Raclette, ost","Kilokalorier":357,"Fett":27.9,"Karbohydrat":0,"Protein":26.4,"Kategori":"Pålegg","underkategori":"Ost-gul"},
{"Matvare":"Ridderost","Kilokalorier":422,"Fett":38,"Karbohydrat":0,"Protein":20,"Kategori":"Pålegg","underkategori":"Ost-gul"},
{"Matvare":"Sveitserost, gulost","Kilokalorier":364,"Fett":28,"Karbohydrat":0,"Protein":28,"Kategori":"Pålegg","underkategori":"Ost-gul"},
{"Matvare":"Taffelost, tomat","Kilokalorier":313,"Fett":24,"Karbohydrat":0.3,"Protein":24,"Kategori":"Pålegg","underkategori":"Ost-gul"},
{"Matvare":"Brie, hvitmuggost","Kilokalorier":360,"Fett":32,"Karbohydrat":0,"Protein":18,"Kategori":"Pålegg","underkategori":"Ost-myk"},
{"Matvare":"Camembert, hvitmuggost","Kilokalorier":328,"Fett":28,"Karbohydrat":0,"Protein":19,"Kategori":"Pålegg","underkategori":"Ost-myk"},
{"Matvare":"Gräddost","Kilokalorier":418,"Fett":38,"Karbohydrat":0,"Protein":19,"Kategori":"Pålegg","underkategori":"Ost-myk"},
{"Matvare":"Mozzarella","Kilokalorier":317,"Fett":23,"Karbohydrat":0.6,"Protein":27,"Kategori":"Pålegg","underkategori":"Ost-myk"},
{"Matvare":"Mozzarella, lettere","Kilokalorier":268,"Fett":16,"Karbohydrat":1,"Protein":30,"Kategori":"Pålegg","underkategori":"Ost-myk"},
{"Matvare":"Chevre, geitost, naturell","Kilokalorier":316,"Fett":28,"Karbohydrat":1,"Protein":15,"Kategori":"Pålegg","underkategori":"Ost-smørbar"},
{"Matvare":"Crème Chérie, mykost","Kilokalorier":335,"Fett":31,"Karbohydrat":0,"Protein":14,"Kategori":"Pålegg","underkategori":"Ost-smørbar"},
{"Matvare":"Geitost, smørbar, naturell, Snøfrisk","Kilokalorier":259,"Fett":25,"Karbohydrat":2,"Protein":6.6,"Kategori":"Pålegg","underkategori":"Ost-smørbar"},
{"Matvare":"Kremost, mager, Philadelphia","Kilokalorier":189,"Fett":16,"Karbohydrat":3.4,"Protein":7.8,"Kategori":"Pålegg","underkategori":"Ost-smørbar"},
{"Matvare":"Kremost, naturell","Kilokalorier":277,"Fett":27,"Karbohydrat":2.7,"Protein":5.7,"Kategori":"Pålegg","underkategori":"Ost-smørbar"},
{"Matvare":"Kremost, Philadelphia","Kilokalorier":281,"Fett":27.3,"Karbohydrat":2.7,"Protein":6.1,"Kategori":"Pålegg","underkategori":"Ost-smørbar"},
{"Matvare":"Magerost, smørbar, 10 % fett","Kilokalorier":162,"Fett":10,"Karbohydrat":0,"Protein":18,"Kategori":"Pålegg","underkategori":"Ost-smørbar"},
{"Matvare":"Magerost, smørbar, 3 % fett","Kilokalorier":100,"Fett":3,"Karbohydrat":0,"Protein":17,"Kategori":"Pålegg","underkategori":"Ost-smørbar"},
{"Matvare":"Magerost, smørbar, 7 % fett","Kilokalorier":130,"Fett":6.5,"Karbohydrat":0,"Protein":18,"Kategori":"Pålegg","underkategori":"Ost-smørbar"},
{"Matvare":"Mascarpone, kremost","Kilokalorier":436,"Fett":44.5,"Karbohydrat":4.3,"Protein":4.6,"Kategori":"Pålegg","underkategori":"Ost-smørbar"},
{"Matvare":"Ricotta, ferskost","Kilokalorier":163,"Fett":13,"Karbohydrat":0.3,"Protein":11.3,"Kategori":"Pålegg","underkategori":"Ost-smørbar"},
{"Matvare":"Italiensk salat, majonessalat, 37 % fett","Kilokalorier":360,"Fett":37.3,"Karbohydrat":4.4,"Protein":1,"Kategori":"Pålegg","underkategori":"Salat"},
{"Matvare":"Rekesalat, majonessalat, 35 % fett","Kilokalorier":359,"Fett":36,"Karbohydrat":5.2,"Protein":3.2,"Kategori":"Pålegg","underkategori":"Salat"},
{"Matvare":"Rødbetsalat, majonessalat, 30 % fett","Kilokalorier":317,"Fett":31.6,"Karbohydrat":6.2,"Protein":1.2,"Kategori":"Pålegg","underkategori":"Salat"},
{"Matvare":"Brelett","Kilokalorier":388,"Fett":40,"Karbohydrat":3,"Protein":4,"Kategori":"Pålegg","underkategori":"Smør"},
{"Matvare":"Bremykt","Kilokalorier":742,"Fett":82,"Karbohydrat":0.5,"Protein":0.5,"Kategori":"Pålegg","underkategori":"Smør"},
{"Matvare":"Margarin, Soft Flora lett","Kilokalorier":364,"Fett":40,"Karbohydrat":0.5,"Protein":0.5,"Kategori":"Pålegg","underkategori":"Smør"},
{"Matvare":"Margarin, Soft Flora, original","Kilokalorier":632,"Fett":70,"Karbohydrat":0.3,"Protein":0.2,"Kategori":"Pålegg","underkategori":"Smør"},
{"Matvare":"Nøttepålegg, med mindre sukker, Nugatti","Kilokalorier":489,"Fett":29.7,"Karbohydrat":41.1,"Protein":6.3,"Kategori":"Pålegg","underkategori":"Søt"},
{"Matvare":"Nøttepålegg, Nugatti","Kilokalorier":525,"Fett":28.1,"Karbohydrat":62.1,"Protein":4.9,"Kategori":"Pålegg","underkategori":"Søt"},
{"Matvare":"Peanøttsmør","Kilokalorier":620,"Fett":51.8,"Karbohydrat":13.1,"Protein":22.8,"Kategori":"Pålegg","underkategori":"Søt"},
{"Matvare":"Prim","Kilokalorier":283,"Fett":8,"Karbohydrat":46,"Protein":6.7,"Kategori":"Pålegg","underkategori":"Søt"},
{"Matvare":"Prim, mager","Kilokalorier":256,"Fett":4,"Karbohydrat":48,"Protein":7,"Kategori":"Pålegg","underkategori":"Søt"},
{"Matvare":"Sjokoladepålegg, Sjokade","Kilokalorier":414,"Fett":19,"Karbohydrat":59,"Protein":1.1,"Kategori":"Pålegg","underkategori":"Søt"},
{"Matvare":"Syltetøy, 40 % bær, 40 % sukker","Kilokalorier":174,"Fett":0.1,"Karbohydrat":42.4,"Protein":0.3,"Kategori":"Pålegg","underkategori":"Søt"},
{"Matvare":"Syltetøy, 45 % bær, 25 % sukker","Kilokalorier":130,"Fett":0.1,"Karbohydrat":31.4,"Protein":0.3,"Kategori":"Pålegg","underkategori":"Søt"},
{"Matvare":"Nudler, med egg, tørr","Kilokalorier":359,"Fett":2,"Karbohydrat":72.6,"Protein":12,"Kategori":"Ris/pasta","underkategori":"Nudler/pasta"},
{"Matvare":"Nudler, uten egg, tørr","Kilokalorier":343,"Fett":3.3,"Karbohydrat":66.4,"Protein":10.2,"Kategori":"Ris/pasta","underkategori":"Nudler/pasta"},
{"Matvare":"Couscous, tørr","Kilokalorier":321,"Fett":0.6,"Karbohydrat":63.6,"Protein":12.8,"Kategori":"Ris/pasta","underkategori":""},
{"Matvare":"Pasta, fullkorn, tørr","Kilokalorier":362,"Fett":2.5,"Karbohydrat":68.3,"Protein":12.6,"Kategori":"Ris/pasta","underkategori":""},
{"Matvare":"Pasta, grønn, fersk, rå","Kilokalorier":229,"Fett":3.9,"Karbohydrat":38.3,"Protein":9.1,"Kategori":"Ris/pasta","underkategori":""},
{"Matvare":"Pasta, naturell, fersk, rå","Kilokalorier":244,"Fett":4,"Karbohydrat":41.5,"Protein":9.5,"Kategori":"Ris/pasta","underkategori":""},
{"Matvare":"Pasta, naturell, tørr","Kilokalorier":347,"Fett":1.3,"Karbohydrat":69.8,"Protein":11.9,"Kategori":"Ris/pasta","underkategori":""},
{"Matvare":"Quinoa, tørr","Kilokalorier":358,"Fett":6.1,"Karbohydrat":58.3,"Protein":14.1,"Kategori":"Ris/pasta","underkategori":""},
{"Matvare":"Ris, polert, Jasminris, tørr","Kilokalorier":354,"Fett":0.7,"Karbohydrat":79.5,"Protein":7.5,"Kategori":"Ris/pasta","underkategori":""},
{"Matvare":"Bremykt, flytende","Kilokalorier":732,"Fett":81,"Karbohydrat":0.5,"Protein":0.3,"Kategori":"Saus/olje","underkategori":"Fet"},
{"Matvare":"Dressing, majonestype, 15 % fett","Kilokalorier":185,"Fett":13.3,"Karbohydrat":14.9,"Protein":1.2,"Kategori":"Saus/olje","underkategori":"Fet"},
{"Matvare":"Dressing, majonestype, 30 % fett","Kilokalorier":295,"Fett":26.4,"Karbohydrat":12.8,"Protein":1.6,"Kategori":"Saus/olje","underkategori":"Fet"},
{"Matvare":"Dressing, majonestype, 40 % fett","Kilokalorier":406,"Fett":40,"Karbohydrat":10.5,"Protein":1,"Kategori":"Saus/olje","underkategori":"Fet"},
{"Matvare":"Dressing, majonestype, 55 % fett","Kilokalorier":518,"Fett":54,"Karbohydrat":4.2,"Protein":3.9,"Kategori":"Saus/olje","underkategori":"Fet"},
{"Matvare":"Maisolje","Kilokalorier":892,"Fett":99,"Karbohydrat":0,"Protein":0.2,"Kategori":"Saus/olje","underkategori":"Fet"},
{"Matvare":"Majones, ekstra lett, 25 % fett","Kilokalorier":257,"Fett":26.1,"Karbohydrat":4.9,"Protein":0.7,"Kategori":"Saus/olje","underkategori":"Fet"},
{"Matvare":"Majones, ekte","Kilokalorier":728,"Fett":79.6,"Karbohydrat":2,"Protein":0.9,"Kategori":"Saus/olje","underkategori":"Fet"},
{"Matvare":"Majones, lett, 50 % fett","Kilokalorier":465,"Fett":48.6,"Karbohydrat":6.1,"Protein":0.7,"Kategori":"Saus/olje","underkategori":"Fet"},
{"Matvare":"Margarin, Melange","Kilokalorier":722,"Fett":80,"Karbohydrat":0.3,"Protein":0.2,"Kategori":"Saus/olje","underkategori":"Fet"},
{"Matvare":"Remulade","Kilokalorier":617,"Fett":65.6,"Karbohydrat":5.6,"Protein":0.9,"Kategori":"Saus/olje","underkategori":"Fet"},
{"Matvare":"Rømmedressing, med urter","Kilokalorier":136,"Fett":11.8,"Karbohydrat":4.7,"Protein":2.8,"Kategori":"Saus/olje","underkategori":"Fet"},
{"Matvare":"Smør","Kilokalorier":742,"Fett":82,"Karbohydrat":0.5,"Protein":0.5,"Kategori":"Saus/olje","underkategori":"Fet"},
{"Matvare":"Brun saus, av blokk","Kilokalorier":55,"Fett":3.5,"Karbohydrat":5,"Protein":1,"Kategori":"Saus/olje","underkategori":"Saus"},
{"Matvare":"Brun saus, kjøttkakesaus, av pulver","Kilokalorier":34,"Fett":1.1,"Karbohydrat":5,"Protein":1,"Kategori":"Saus/olje","underkategori":"Saus"},
{"Matvare":"Brun saus, med løk, av pulver","Kilokalorier":39,"Fett":1.5,"Karbohydrat":5.5,"Protein":1,"Kategori":"Saus/olje","underkategori":"Saus"},
{"Matvare":"Ketchup, tomatketchup","Kilokalorier":107,"Fett":0.4,"Karbohydrat":23.5,"Protein":1.8,"Kategori":"Saus/olje","underkategori":"Saus"},
{"Matvare":"Pesto, grønn, kjøpt","Kilokalorier":520,"Fett":52.9,"Karbohydrat":4.9,"Protein":5.2,"Kategori":"Saus/olje","underkategori":"saus"},
{"Matvare":"Sennep","Kilokalorier":158,"Fett":6.4,"Karbohydrat":18.5,"Protein":5.7,"Kategori":"Saus/olje","underkategori":"saus"},
{"Matvare":"Sennepssaus","Kilokalorier":441,"Fett":39.8,"Karbohydrat":17.8,"Protein":2.6,"Kategori":"Saus/olje","underkategori":"saus"},
{"Matvare":"Tomatpuré, hermetisk","Kilokalorier":84,"Fett":0.2,"Karbohydrat":14.5,"Protein":4.8,"Kategori":"Saus/olje","underkategori":"saus"},
{"Matvare":"Buljongpulver","Kilokalorier":144,"Fett":4.5,"Karbohydrat":9,"Protein":17,"Kategori":"Saus/olje","underkategori":"Tørr"},
{"Matvare":"Fiskeboller, kjølevare","Kilokalorier":68,"Fett":0.9,"Karbohydrat":5.5,"Protein":9.5,"Kategori":"Sjømat","underkategori":"Bearbeidet"},
{"Matvare":"Fiskegrateng, kjøpt","Kilokalorier":119,"Fett":4.6,"Karbohydrat":11.6,"Protein":7.5,"Kategori":"Sjømat","underkategori":"Bearbeidet"},
{"Matvare":"Fiskekaker, kjøpt","Kilokalorier":110,"Fett":4.2,"Karbohydrat":5.9,"Protein":11.8,"Kategori":"Sjømat","underkategori":"Bearbeidet"},
{"Matvare":"Fiskekarbonader, kjøpt","Kilokalorier":107,"Fett":3.7,"Karbohydrat":6.5,"Protein":11.5,"Kategori":"Sjømat","underkategori":"Bearbeidet"},
{"Matvare":"Fiskepudding","Kilokalorier":72,"Fett":1,"Karbohydrat":7.5,"Protein":8.1,"Kategori":"Sjømat","underkategori":"Bearbeidet"},
{"Matvare":"Fiskepudding, fløtepudding","Kilokalorier":102,"Fett":4.6,"Karbohydrat":7.2,"Protein":8,"Kategori":"Sjømat","underkategori":"Bearbeidet"},
{"Matvare":"Alaska pollock, rå","Kilokalorier":72,"Fett":0.7,"Karbohydrat":0,"Protein":16.4,"Kategori":"Sjømat","underkategori":"Fisk"},
{"Matvare":"Blåkveite, rå/kaldrøkt","Kilokalorier":155,"Fett":11,"Karbohydrat":0,"Protein":14,"Kategori":"Sjømat","underkategori":"Fisk"},
{"Matvare":"Blålange, rå","Kilokalorier":64,"Fett":0.1,"Karbohydrat":0,"Protein":15.7,"Kategori":"Sjømat","underkategori":"Fisk"},
{"Matvare":"Breiflabb, rå","Kilokalorier":64,"Fett":0.1,"Karbohydrat":0,"Protein":15.8,"Kategori":"Sjømat","underkategori":"Fisk"},
{"Matvare":"Brosme, rå","Kilokalorier":66,"Fett":0.2,"Karbohydrat":0,"Protein":16.1,"Kategori":"Sjømat","underkategori":"Fisk"},
{"Matvare":"Gjedde, rå","Kilokalorier":83,"Fett":0.2,"Karbohydrat":0,"Protein":20.2,"Kategori":"Sjømat","underkategori":"Fisk"},
{"Matvare":"Hvitting, rå","Kilokalorier":79,"Fett":0.6,"Karbohydrat":0,"Protein":18.3,"Kategori":"Sjømat","underkategori":"Fisk"},
{"Matvare":"Hyse, kolje, rå","Kilokalorier":68,"Fett":0.2,"Karbohydrat":0,"Protein":16.6,"Kategori":"Sjømat","underkategori":"Fisk"},
{"Matvare":"Håbrann, rå","Kilokalorier":85,"Fett":0.4,"Karbohydrat":0,"Protein":20.3,"Kategori":"Sjømat","underkategori":"Fisk"},
{"Matvare":"Kveite, hellefisk, oppdrett, rå","Kilokalorier":102,"Fett":2.4,"Karbohydrat":0,"Protein":20,"Kategori":"Sjømat","underkategori":"Fisk"},
{"Matvare":"Lange, rå","Kilokalorier":72,"Fett":0.2,"Karbohydrat":0,"Protein":17.5,"Kategori":"Sjømat","underkategori":"Fisk"},
{"Matvare":"Pangasius, rå","Kilokalorier":63,"Fett":1.1,"Karbohydrat":0,"Protein":13.1,"Kategori":"Sjømat","underkategori":"Fisk"},
{"Matvare":"Pigghå, håbrann, rå","Kilokalorier":129,"Fett":6.4,"Karbohydrat":0,"Protein":17.9,"Kategori":"Sjømat","underkategori":"Fisk"},
{"Matvare":"Piggvar, rå","Kilokalorier":85,"Fett":2.4,"Karbohydrat":0,"Protein":15.9,"Kategori":"Sjømat","underkategori":"Fisk"},
{"Matvare":"Rødspette, rå","Kilokalorier":91,"Fett":2.6,"Karbohydrat":0,"Protein":16.8,"Kategori":"Sjømat","underkategori":"Fisk"},
{"Matvare":"Sei, rå","Kilokalorier":69,"Fett":0.3,"Karbohydrat":0,"Protein":16.5,"Kategori":"Sjømat","underkategori":"Fisk"},
{"Matvare":"Sik, rå","Kilokalorier":89,"Fett":0.6,"Karbohydrat":0,"Protein":20.9,"Kategori":"Sjømat","underkategori":"Fisk"},
{"Matvare":"Skate, rå","Kilokalorier":58,"Fett":0.2,"Karbohydrat":0,"Protein":14,"Kategori":"Sjømat","underkategori":"Fisk"},
{"Matvare":"Steinbit, rå","Kilokalorier":97,"Fett":2.5,"Karbohydrat":0,"Protein":18.6,"Kategori":"Sjømat","underkategori":"Fisk"},
{"Matvare":"Torsk, uspesifisert, rå","Kilokalorier":81,"Fett":1,"Karbohydrat":0,"Protein":18.1,"Kategori":"Sjømat","underkategori":"Fisk"},
{"Matvare":"Uer, rå","Kilokalorier":94,"Fett":2.8,"Karbohydrat":0,"Protein":17.1,"Kategori":"Sjømat","underkategori":"Fisk"},
{"Matvare":"Åbor, abbor, rå","Kilokalorier":85,"Fett":0.6,"Karbohydrat":0,"Protein":19.8,"Kategori":"Sjømat","underkategori":"Fisk"},
{"Matvare":"Hval, kjøtt, rå","Kilokalorier":120,"Fett":2.1,"Karbohydrat":0,"Protein":25.2,"Kategori":"Sjømat","underkategori":"Fisk-diverse"},
{"Matvare":"Kaviar, av torskerogn","Kilokalorier":413,"Fett":35.2,"Karbohydrat":13.7,"Protein":10.5,"Kategori":"Sjømat","underkategori":"Fisk-diverse"},
{"Matvare":"Klippfisk, saltet og tørket","Kilokalorier":271,"Fett":1.2,"Karbohydrat":0,"Protein":65,"Kategori":"Sjømat","underkategori":"Fisk-diverse"},
{"Matvare":"Lutefisk, tørr vare, rå","Kilokalorier":50,"Fett":0.7,"Karbohydrat":0,"Protein":10.9,"Kategori":"Sjømat","underkategori":"Fisk-diverse"},
{"Matvare":"Rogn, torsk, presset, hermetisk","Kilokalorier":125,"Fett":1.9,"Karbohydrat":0,"Protein":27.1,"Kategori":"Sjømat","underkategori":"Fisk-diverse"},
{"Matvare":"Sjøtunge, rå","Kilokalorier":64,"Fett":0.5,"Karbohydrat":0,"Protein":14.8,"Kategori":"Sjømat","underkategori":"Fisk-diverse"},
{"Matvare":"Tørrfisk","Kilokalorier":327,"Fett":1.4,"Karbohydrat":0,"Protein":78.5,"Kategori":"Sjømat","underkategori":"Fisk-diverse"},
{"Matvare":"Makrell, mai-juni, rå","Kilokalorier":123,"Fett":5.4,"Karbohydrat":0,"Protein":18.6,"Kategori":"Sjømat","underkategori":"Fisk-fet"},
{"Matvare":"Makrell, vill (høst), rå","Kilokalorier":293,"Fett":25,"Karbohydrat":0,"Protein":17,"Kategori":"Sjømat","underkategori":"Fisk-fet"},
{"Matvare":"Sild, fetsild, sommersild, rå","Kilokalorier":293,"Fett":25,"Karbohydrat":0,"Protein":17,"Kategori":"Sjømat","underkategori":"Fisk-fet"},
{"Matvare":"Sild, fetsild/sommersild, kokt","Kilokalorier":349,"Fett":29.8,"Karbohydrat":0,"Protein":20.2,"Kategori":"Sjømat","underkategori":"Fisk-fet"},
{"Matvare":"Sild, kryddersild","Kilokalorier":154,"Fett":12,"Karbohydrat":0,"Protein":11.5,"Kategori":"Sjømat","underkategori":"Fisk-fet"},
{"Matvare":"Sild, marinert, sennepssild","Kilokalorier":250,"Fett":13.6,"Karbohydrat":25.5,"Protein":6.1,"Kategori":"Sjømat","underkategori":"Fisk-fet"},
{"Matvare":"Sild, storsild, vintersild, rå","Kilokalorier":187,"Fett":14,"Karbohydrat":0,"Protein":15.2,"Kategori":"Sjømat","underkategori":"Fisk-fet"},
{"Matvare":"Sild, sursild, innlagt, avrent","Kilokalorier":190,"Fett":11.7,"Karbohydrat":11.1,"Protein":9.9,"Kategori":"Sjømat","underkategori":"Fisk-fet"},
{"Matvare":"Ål, rå","Kilokalorier":362,"Fett":32.5,"Karbohydrat":0,"Protein":17.3,"Kategori":"Sjømat","underkategori":"Fisk-fet"},
{"Matvare":"Laks, oppdrett, rå","Kilokalorier":224,"Fett":16,"Karbohydrat":0,"Protein":20,"Kategori":"Sjømat","underkategori":"Fisk-rød"},
{"Matvare":"Laks, røkt","Kilokalorier":225,"Fett":14.7,"Karbohydrat":0,"Protein":23.2,"Kategori":"Sjømat","underkategori":"Fisk-rød"},
{"Matvare":"Røye, rå","Kilokalorier":128,"Fett":7.1,"Karbohydrat":0,"Protein":16.1,"Kategori":"Sjømat","underkategori":"Fisk-rød"},
{"Matvare":"Tunfisk, i gele, hermetisk","Kilokalorier":70,"Fett":0.4,"Karbohydrat":0,"Protein":16.5,"Kategori":"Sjømat","underkategori":"Fisk-rød"},
{"Matvare":"Tunfisk, i olje, avrent, hermetisk","Kilokalorier":259,"Fett":18.9,"Karbohydrat":0,"Protein":22.3,"Kategori":"Sjømat","underkategori":"Fisk-rød"},
{"Matvare":"Tunfisk, i vann, avrent, hermetisk","Kilokalorier":105,"Fett":1,"Karbohydrat":0,"Protein":24.1,"Kategori":"Sjømat","underkategori":"Fisk-rød"},
{"Matvare":"Tunfisk, makrellstørje, rå","Kilokalorier":105,"Fett":1,"Karbohydrat":0,"Protein":24,"Kategori":"Sjømat","underkategori":"Fisk-rød"},
{"Matvare":"Ørret, oppdrett, rå","Kilokalorier":166,"Fett":10,"Karbohydrat":0,"Protein":19,"Kategori":"Sjømat","underkategori":"Fisk-rød"},
{"Matvare":"Ørret, sjøørret, rå","Kilokalorier":110,"Fett":3.3,"Karbohydrat":0,"Protein":20,"Kategori":"Sjømat","underkategori":"Fisk-rød"},
{"Matvare":"Akkar, tiarmet blekksprut, rå","Kilokalorier":77,"Fett":1.7,"Karbohydrat":0,"Protein":15.4,"Kategori":"Sjømat","underkategori":"Skjell/bløtdyr"},
{"Matvare":"Blåskjell, rå","Kilokalorier":54,"Fett":1.4,"Karbohydrat":0,"Protein":10.4,"Kategori":"Sjømat","underkategori":"Skjell/bløtdyr"},
{"Matvare":"Hummer, kokt","Kilokalorier":66,"Fett":0.6,"Karbohydrat":0,"Protein":15.2,"Kategori":"Sjømat","underkategori":"Skjell/bløtdyr"},
{"Matvare":"Kamskjell, rå","Kilokalorier":81,"Fett":1.1,"Karbohydrat":0,"Protein":17.9,"Kategori":"Sjømat","underkategori":"Skjell/bløtdyr"},
{"Matvare":"Kongereke, rå","Kilokalorier":77,"Fett":0.7,"Karbohydrat":0,"Protein":17.6,"Kategori":"Sjømat","underkategori":"Skjell/bløtdyr"},
{"Matvare":"Krabbe, kokt","Kilokalorier":108,"Fett":1.8,"Karbohydrat":0,"Protein":22.9,"Kategori":"Sjømat","underkategori":"Skjell/bløtdyr"},
{"Matvare":"Kreps, kokt","Kilokalorier":54,"Fett":1.3,"Karbohydrat":0,"Protein":10.7,"Kategori":"Sjømat","underkategori":"Skjell/bløtdyr"},
{"Matvare":"Reker, i lake, avrent","Kilokalorier":58,"Fett":0.6,"Karbohydrat":0,"Protein":13.2,"Kategori":"Sjømat","underkategori":"Skjell/bløtdyr"},
{"Matvare":"Snegler, hermetisk","Kilokalorier":77,"Fett":1.4,"Karbohydrat":0,"Protein":16.1,"Kategori":"Sjømat","underkategori":"Skjell/bløtdyr"},
{"Matvare":"Strandsnegle, norsk","Kilokalorier":87,"Fett":1.4,"Karbohydrat":3.3,"Protein":15.2,"Kategori":"Sjømat","underkategori":"Skjell/bløtdyr"},
{"Matvare":"Østers, rå","Kilokalorier":59,"Fett":2.4,"Karbohydrat":0,"Protein":9.3,"Kategori":"Sjømat","underkategori":"Skjell/bløtdyr"},
{"Matvare":"Sashimi, kveite","Kilokalorier":113,"Fett":4.3,"Karbohydrat":0,"Protein":18.5,"Kategori":"Sjømat","underkategori":"Sushi"},
{"Matvare":"Sashimi, laks","Kilokalorier":224,"Fett":16,"Karbohydrat":0,"Protein":20,"Kategori":"Sjømat","underkategori":"Sushi"},
{"Matvare":"Sashimi, tunfisk","Kilokalorier":105,"Fett":1,"Karbohydrat":0,"Protein":24,"Kategori":"Sjømat","underkategori":"Sushi"},
{"Matvare":"Sushi, maki, kveite","Kilokalorier":116,"Fett":2.4,"Karbohydrat":18.1,"Protein":5.1,"Kategori":"Sjømat","underkategori":"Sushi"},
{"Matvare":"Sushi, maki, laks","Kilokalorier":134,"Fett":4.3,"Karbohydrat":18.1,"Protein":5.3,"Kategori":"Sjømat","underkategori":"Sushi"},
{"Matvare":"Sushi, maki, tunfisk","Kilokalorier":115,"Fett":1.9,"Karbohydrat":18.1,"Protein":5.9,"Kategori":"Sjømat","underkategori":"Sushi"},
{"Matvare":"Sushi, nigiri, kveite","Kilokalorier":114,"Fett":1.4,"Karbohydrat":17.8,"Protein":7.3,"Kategori":"Sjømat","underkategori":"Sushi"},
{"Matvare":"Sushi, nigiri, laks","Kilokalorier":147,"Fett":5,"Karbohydrat":17.8,"Protein":7.8,"Kategori":"Sjømat","underkategori":"Sushi"},
{"Matvare":"Sushi, nigiri, tunfisk","Kilokalorier":112,"Fett":0.5,"Karbohydrat":17.8,"Protein":9,"Kategori":"Sjømat","underkategori":"Sushi"},
{"Matvare":"Ostepop","Kilokalorier":495,"Fett":30.2,"Karbohydrat":44.4,"Protein":9.8,"Kategori":"Snacks","underkategori":"Salt"},
{"Matvare":"Popcorn, kjøpt","Kilokalorier":398,"Fett":14.5,"Karbohydrat":51.4,"Protein":10.1,"Kategori":"Snacks","underkategori":"Salt"},
{"Matvare":"Potetchips","Kilokalorier":517,"Fett":31.5,"Karbohydrat":50.5,"Protein":5.2,"Kategori":"Snacks","underkategori":"Salt"},
{"Matvare":"Saltstenger","Kilokalorier":380,"Fett":6.3,"Karbohydrat":68.1,"Protein":10.5,"Kategori":"Snacks","underkategori":"Salt"},
{"Matvare":"Tortillachips, nachochips","Kilokalorier":475,"Fett":22.4,"Karbohydrat":57.4,"Protein":7.4,"Kategori":"Snacks","underkategori":"Salt"},
{"Matvare":"Sjokolade, hvit","Kilokalorier":544,"Fett":30.9,"Karbohydrat":58.3,"Protein":8,"Kategori":"Snacks","underkategori":"Sjokolade"},
{"Matvare":"Sjokolade, kokesjokolade, lys","Kilokalorier":527,"Fett":29.5,"Karbohydrat":56.7,"Protein":7,"Kategori":"Snacks","underkategori":"Sjokolade"},
{"Matvare":"Sjokolade, mørk, 70 % kakao","Kilokalorier":584,"Fett":46.5,"Karbohydrat":33.2,"Protein":7,"Kategori":"Snacks","underkategori":"Sjokolade"},
{"Matvare":"Sjokolade, Snickers","Kilokalorier":498,"Fett":28.2,"Karbohydrat":52.2,"Protein":7.5,"Kategori":"Snacks","underkategori":"Sjokolade"},
{"Matvare":"Sjokoladepudding, Piano","Kilokalorier":123,"Fett":3.9,"Karbohydrat":18,"Protein":3.3,"Kategori":"Snacks","underkategori":"Sjokolade"},
{"Matvare":"Geléfrukt, Seigmenn","Kilokalorier":292,"Fett":0,"Karbohydrat":65.5,"Protein":7.6,"Kategori":"Snacks","underkategori":"Søt"},
{"Matvare":"Iskrem, fløte, med sjokoladebiter","Kilokalorier":241,"Fett":12.6,"Karbohydrat":28.1,"Protein":3.5,"Kategori":"Snacks","underkategori":"Søt"},
{"Matvare":"Karamell","Kilokalorier":376,"Fett":22,"Karbohydrat":42.9,"Protein":1.5,"Kategori":"Snacks","underkategori":"Søt"},
{"Matvare":"Karamellpudding, Piano","Kilokalorier":128,"Fett":5.8,"Karbohydrat":16,"Protein":2.8,"Kategori":"Snacks","underkategori":"Søt"},
{"Matvare":"Kokosbolle","Kilokalorier":376,"Fett":14.8,"Karbohydrat":55.2,"Protein":4.5,"Kategori":"Snacks","underkategori":"Søt"},
{"Matvare":"Marsipan, 50 % mandler","Kilokalorier":508,"Fett":27.5,"Karbohydrat":52.7,"Protein":10.5,"Kategori":"Snacks","underkategori":"Søt"},
{"Matvare":"Marsipanbrød, med sjokoladetrekk","Kilokalorier":514,"Fett":29.5,"Karbohydrat":52,"Protein":9,"Kategori":"Snacks","underkategori":"Søt"},
{"Matvare":"Saftis, Lollipop","Kilokalorier":120,"Fett":3.5,"Karbohydrat":22,"Protein":0.1,"Kategori":"Snacks","underkategori":"Søt"},
{"Matvare":"Vaniljesaus, Piano","Kilokalorier":147,"Fett":8.4,"Karbohydrat":15,"Protein":2.7,"Kategori":"Snacks","underkategori":"Søt"}
];
// testing values for each kcal, Fett, Karbohydrat, Proteiner
// each has a limit: kcal 1000, and the others 100 (as they are percentage of total weight)
var str = "";
for (i in mat) {
      if (mat[i].Kilokalorier>1000) {str += "Kcal har avvik for"+mat[i].Matvare+"<br>";}
      if (mat[i].Fett>100) {str += "Fett har avvik for"+mat[i].Matvare+"<br>";}
      if (mat[i].Karbohydrat>100) {str += "Karbo har avvik for"+mat[i].Matvare+"<br>";}
      if (mat[i].Protein>100) {str += "Protein har avvik for"+mat[i].Matvare+"<br>";}
    }
    if (str=="") {str = "ingen avvik funnet i totalt "+i+" JSON data <br>"}
document.getElementById("paraId").innerHTML = str;
